### ISSUE TITLE
Pepper expects <output_file>_pepper_polished.fa to already exist

### ISSUE THREAD

**Issue by TimD1** [kishwarshafin/pepper#10]
When running PEPPER (either `polish` or just the final `stitch` script) with the following arguments:
```
pepper polish \
-b ./aligned/calls_to_ref.bam \
-f ~/datasets/bacteria/klebsiella_pneumoniae_NUH29/reference.fasta \
-m ~/software/pepper/models/PromethION_r941_guppy305_HAC_microbial.pkl \
-o pepper \
-t 8
```
 it crashes with the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '/data/klebsiella_pneumoniae_NUH29/guppy_360_hac/pepper_pepper_polished.fa'`

Creating an empty file under this name beforehand temporarily fixes the issue. This is on commit `7942db`, current master.

**Comment by kishwarshafin** [comment]
Hi @TimD1 ,

can you please see if the error exists even if you are using absolute path for the parameters? 

```bash
pepper polish \
-b /data/klebsiella_pneumoniae_NUH29/guppy_360_hac/aligned/calls_to_ref.bam \
-f ~/datasets/bacteria/klebsiella_pneumoniae_NUH29/reference.fasta \
-m ~/software/pepper/models/PromethION_r941_guppy305_HAC_microbial.pkl \
-o /data/klebsiella_pneumoniae_NUH29/guppy_360_hac/pepper \
-t 8
```

**Comment by TimD1** [comment]
Just tested it, I get the same error even if all filepaths are absolute.

**Comment by kishwarshafin** [comment]
Can you please make sure you have permission to write in that directory? I can't generate this error locally. What OS are you using?

**Comment by TimD1** [comment]
Yep, I definitely have read/write permissions. I'm on Ubuntu 16.04.6 LTS

**Comment by kishwarshafin** [comment]
Hi @TimD1 ,

I am sorry that you are still seeing this error. I installed and ran PEPPER on an Ubuntu 16.04 LTS GCP instance without any problem. 

Also, can you please make sure to do a 
```bash
cd /path/to/pepper
make clean
git pull origin master
make install
```

And then can you please run this upload the log file here so I can look into the log file to see where the error is happening?
```bash
pepper polish \
-b /path/to/aligned/calls_to_ref.bam \
-f /path/to/datasets/bacteria/klebsiella_pneumoniae_NUH29/reference.fasta \
-m /path/to/software/pepper/models/PromethION_r941_guppy305_HAC_microbial.pkl \
-o /path/to/pepper_output \
-t 8 2>&1 | tee pepper_run.log
```

**Comment by TimD1** [comment]
No problem. I found an easy workaround, just wanted to let you know that it doesn't run cleanly with my setup. 

I've attached the log file:
[pepper_run.log](https://github.com/kishwarshafin/pepper/files/5053311/pepper_run.log)

**Comment by kishwarshafin** [comment]
Hi @TimD1 , 

Thanks for the error log. It's a python3.5 and `pathlib` issue ([#similar issue here](https://github.com/18F/domain-scan/issues/261)). You shouldn't have this issue if you are using python3.6+ which I've been using for all my tests. 

I'll take care of this issue during the next major release as it sounds like you already have a workaround.
