### ISSUE TITLE
Getting phased VCF on CCS/HiFi data

### ISSUE THREAD

**Issue by SHuang-Broad** [kishwarshafin/pepper#101]
This is a followup to #88, regarding an end-to-end pipeline for CCS/HiFi data.

I've followed the advice there and provided the Pepper-generated phased bam to DV, and received VCF and gVCF from it (yay!).

Now my question is: how do I obtain the phased VCF?

My understanding is that, DV-Pepper pipeline works in 5 stages for ONT data, judged from the log file outputs:

1. 1_pepper_snp.log
2. 2_margin_haplotag.log
3. 3_pepper_hp.log
4. 4_DeepVariant.log and
5. 5_margin_phase.log

It looks like for CCS data, Pepper stops after step 2. And users are expected to run step 4 separately (which I did).

How, then, would I run step 5? Does it need outputs from step 3, and if so, how would I run that?

Thanks!
Steve

**Comment by tpesout** [comment]
Hi Steve, 

The command to phase the VCF is almost the same as was used to haplotag the BAM, except with `-M` instead of `-V`, a slightly different parameters file, and a different output name (just so you don't overwrite the previous output).  Assuming the same mounting parameters for docker, you should be able to use this command:

`time margin phase /app/input/YOUR.bam /app/input/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa /app/output/YOUR.vcf.gz /opt/margin_dir/params/misc/allParams.phase_vcf.json -t 16 -r chr1 -M -o /app/output/PEPPER_MARGIN_DV 2>&1 | tee /app/output/logs/5_margin_phase_vcf.log;`

Please let me know if this works for you!

-Trevor

**Comment by SHuang-Broad** [comment]
Thanks, Trevor!

I see there are several options json files as listed below, where can I find documentations for them?


```bash

$ find /opt/margin_dir/params/ -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'
| | | |____
| | | |____base_params.json
| | | |____pacbio
| | | | |____hifi
| | | | | |____allParams.hifi.json
| | | |____misc
| | | | |____allParams.no_rle.json
| | | | |____allParams.ccs_haplotag.json
| | | | |____allParams.phase_vcf.json
| | | | |____allParams.ont_haplotag.json
| | | |____ont
| | | | |____r9.4
| | | | | |____allParams.np.microbial.r94-g344.json
| | | | | |____allParams.np.human.r94-g344.json
| | | | | |____allParams.np.human.r94-g305.json
| | | | | |____allParams.np.human.r94-g360.json
| | | | | |____allParams.np.microbial.r94-g305.json
| | | | | |____allParams.np.human.r94-g235.json
| | | | |____r10.3
| | | | | |____allParams.np.microbial.r103g324.json
| | | | | |____allParams.np.human.r103-g3210.json
```

Thanks

**Comment by SHuang-Broad** [comment]
A follow up question, for the input bam to margin phase, would it make sense to use the haplotaged bam from `Pepper` (which I assume was generated from `margin`), and hope it runs faster? Or will that fail completely?

Thanks!

**Comment by tpesout** [comment]
Hi Steve, glad to hear it worked.

Most of the parameters are for `margin polish`, an assembly polisher which we developed a few years ago (the PMDV assembly polishing pipeline performs better, so this tool is no longer recommended).  The differences between these are related to homopolymer models from specific basecallers.  The three params we have for `margin phase` are `ccs_haplotag`, `ont_haplotag`, and `phase_vcf` which serve to haplotag reads for PacBio HiFi and ONT, and to phase variants.  

Which BAM is used (original or already-tagged) doesn't matter, as margin will generate new read tagging and variant phasing based on the new variants.  It's just important that you use the final VCF produced by DeepVariant.

**Comment by kishwarshafin** [comment]
@SHuang-Broad , closing this issue as it seems to be resolved. Please reopen if you have further queries.

**Comment by SHuang-Broad** [comment]
Hi @kishwarshafin and @tpesout , sorry for late in replying (been on vacation and slowly catching up).

I tried the suggested command, and there's one issue. The most relevant error message is 
```
Could not open file /cromwell_root/margin_output/HG00514.pepper.chunks.csv for 'w'
```
I've seen `*.chunks.csv` generated in the first stage in the DVPepper pipeline, but I wasn't quite sure it that would be needed for `margin phase` to run.


------

Here's the command  and the log


```bash
time margin phase \
    ~{bam} \
    ~{ref_fasta} \
    ~{unphased_vcf} \
    /opt/margin_dir/params/misc/allParams.phase_vcf.json \
    -t "${num_core}" \
    -M \
    -o "~{output_root}/~{prefix}" \
    2>&1 | tee "~{output_root}/logs/5_margin_phase_vcf.log"
```

```bash

Running OpenMP with 16 threads.
> Parsing model parameters from file: /opt/margin_dir/params/misc/allParams.phase_vcf.json
> Parsed 6344736 HET VCF entries from /cromwell_root/broad-dsde-methods-long-reads-outgoing/aou-long-reads-pacbio/PBCCSWholeGenome/HG00514/variants/small/HG00514.deepvariant_pepper.deepvariant_pepper.vcf.gz; skipped 0 for region, 1298500 for not being PASS, 1795276 for being homozygous, 963160 for being INDEL
> Set up bam chunker in 1342s with chunk size 100000 and overlap 10000 (for region=chr9,chrY,chr20,chr4,chr15,chr10,chr8,chr21,chr12,chr22,chr17,chr7,chr5,chr3,chr1,chr2,chr13,chr6,chr14,chr11,chr16,chrX,chr19,chr18), resulting in 30191 total chunks
Could not open file /cromwell_root/margin_output/HG00514.pepper.chunks.csv for 'w'


real 22m40.979s
user 22m12.527s
sys 1m50.662s

```

I'm using the docker version `kishwars/pepper_deepvariant:r0.4.1`.

Thanks!

**Comment by tpesout** [comment]
Hi, so sorry for the delay.  This issue is that margin does not create directories, so it fails to open the file for writing because (I assume) the directory /cromwell_root/margin_output/ doesn't exist.  The chunks file isn't necessary to run, it's generated by margin to describe where chunk boundaries are.  

It looks like you might be using cromwell to run a WDL script?  Adding a `mkdir -p ~{output_root}` to your script or changing your invocation to just use `-o ~{prefix}` should both fix your issue.

**Comment by SHuang-Broad** [comment]
Ah, awesome! I'll test today and report back.

**Comment by SHuang-Broad** [comment]
See updates in #107
