### ISSUE TITLE
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by sbassi** [kishwarshafin/pepper#103]
Got this error when running it from a docker. This is the command:

```
sudo docker run --ipc=host -v "/home/dnalinux/efs/PEPPER/input/data":"/home/dnalinux/efs/PEPPER/input/data" -v "/home/dnalinux/efs/PEPPER/output":"/home/dnalinux/efs/PEPPER/output" kishwars/pepper_deepvariant:r0.5 run_pepper_margin_deepvariant call_variant -b "/home/dnalinux/efs/PEPPER/input/data/VNS_Yellow_pea.bam" -f "/home/dnalinux/efs/PEPPER/input/data/Pisum_sativum_v1a.fa" -o "/home/dnalinux/efs/PEPPER/output" -p "VNS_Yellow_Pea_PEPPER_Margin_DeepVarian" -t 32 --ont
```

This is part of the error log:

```
09-24-2021 20:25:08] INFO: [THREAD 00] 530/556 COMPLETE (95%) [ELAPSED TIME: 22
 Min 49 Sec]
[09-24-2021 20:25:12] INFO: [THREAD 00] 540/556 COMPLETE (97%) [ELAPSED TIME: 22
 Min 53 Sec]
[09-24-2021 20:25:22] INFO: [THREAD 00] 550/556 COMPLETE (98%) [ELAPSED TIME: 23
 Min 3 Sec]
[09-24-2021 20:25:34] INFO: THREAD 0 FINISHED SUCCESSFULLY.
[09-24-2021 20:27:41] INFO: FINISHED IMAGE GENERATION
[09-24-2021 20:27:41] INFO: TOTAL ELAPSED TIME FOR GENERATING IMAGES: 25 Min 22 
Sec
[09-24-2021 20:27:41] INFO: STEP 2/3 RUNNING INFERENCE
[09-24-2021 20:27:41] INFO: OUTPUT: /home/dnalinux/efs/PEPPER/output/pepper/predictions_09242021_200218/
[09-24-2021 20:27:41] INFO: DISTRIBUTED CPU SETUP.
[09-24-2021 20:27:41] INFO: TOTAL CALLERS: 90
[09-24-2021 20:27:41] INFO: THREADS PER CALLER: 1
[09-24-2021 20:27:43] INFO: MODEL LOADING TO ONNX
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
ERROR: A process in the process pool was terminated abruptly while the future was
```

and also this:

```
  File "/usr/local/lib/python3.8/dist-packages/pepper_variant/pepper_variant.py", line 59, in main
    call_variant(FLAGS.bam,
  File "/usr/local/lib/python3.8/dist-packages/pepper_variant/modules/python/CallVariant.py", line 127, in call_variant
    process_candidates(prediction_output_directory,
  File "/usr/local/lib/python3.8/dist-packages/pepper_variant/modules/python/FindCandidates.py", line 197, in process_candidates
    candidate_finder(input_dir,
  File "/usr/local/lib/python3.8/dist-packages/pepper_variant/modules/python/FindCandidates.py", line 163, in candidate_finder
    with h5py.File(prediction_file, 'r') as hdf5_file:
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)
```

But I think this last error is product of the others.

**Comment by kishwarshafin** [comment]
hi @sbassi , 

Any chance you can share the bam and fasta so I can look at this locally? I haven't been able to reproduce this error although it was reported before. Even one contig worth of data would be enough.

**Comment by sbassi** [comment]
hello, thank you for your answer, here is the file:

<deleted>

Warning: 25Gb.

Tell me when you are done so I delete this object.

**Comment by kishwarshafin** [comment]
@sbassi , 

I also need the fasta/reference file.

**Comment by sbassi** [comment]
here is the reference file:

https://toyoko-data.s3.us-west-2.amazonaws.com/Pisum_sativum_v1a.fa

I had to cancel the read for the other file.

**Comment by kishwarshafin** [comment]
@sbassi ,

Ah, sorry, it got cancelled before the download could complete, now I'm getting:
```bash
aws s3 --no-sign-request cp s3://toyoko-data/VNS_Yellow_pea_merged_bam_file.sort.bam .
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```
The reference download is done, can you please make the bam file available again?

**Comment by sbassi** [comment]
Can you please send me your email to sbassi@gmail.com so I send you a private link to the file?

**Comment by sbassi** [comment]
NVM, I found your email in your GH profile, so I will send you a new link there.

**Comment by kishwarshafin** [comment]
@sbassi ,

Can you please provide me the following information for your data:
1) Basecaller version used
2) Expected coverage
3) Aligner used

**Comment by sbassi** [comment]
hac_9.4.1 . (Guppy) as the base model (high accuracy R9.4 flow cell)
33X expected coverage
and was aligned with minimap

**Comment by kishwarshafin** [comment]
@sbassi 

Do you know the exact version of guppy you used? These don’t look like reads from guppy 5.0.7_sup mode, the amount of variants is very very high which is possibly because the error rate of the reads is too high?

**Comment by sbassi** [comment]
we had multiple bam files from one genotype. we sorted, indexed and merged them with samtools merge. Can you look at one of those initial bam files and see if he sees the same error rate in sequencing? Just to check if the error is related to these processes. I will send you by email the URL of some bam files for you to check.

**Comment by sbassi** [comment]
The guppy version was 5.0.11

**Comment by kishwarshafin** [comment]
@sbassi ,

Thank you. The difference is maybe the heterozygosity of the genome then. PEPPER is initially picking up way too many candidates, so when it goes to the inference step, it runs out of memory. I will work on capping the memory usage but the current setup is a bit tricky. I'll try to post a solution as soon as I have something.

**Comment by sbassi** [comment]
Thank you for your help. I did increase the RAM in the VM, and got the same, maybe a capping is needed. 
You may find this useful.

![Screen Shot 2021-09-27 at 1 45 39 PM](https://user-images.githubusercontent.com/238517/134976052-02433668-b2fe-48da-8622-cf27e5ade266.png)
![Screen Shot 2021-09-27 at 1 46 24 PM](https://user-images.githubusercontent.com/238517/134976054-fe8cbdcb-f7f7-41e7-a2fc-bf3382ec7fc4.png)
![Screen Shot 2021-09-27 at 1 46 42 PM](https://user-images.githubusercontent.com/238517/134976056-166bf9a8-2c44-4105-8966-4225be082220.png)

**Comment by kishwarshafin** [comment]
@sbassi , thanks, I was able to reproduce the error internally and I think we can fix this, it's just going to take a little bit of time. Meanwhile, you can run the variant calling pipeline only on one contig using `-r`. For example, you can run the following command to run it on `chr4LG4` contig. This way the memory explosion does not happen. You can navigate the variants and see if they make sense to you. It's just to make sure you can still make some progress with your analysis while we fix this.
```bash
sudo docker run --ipc=host \
-v "/home/dnalinux/efs/PEPPER/input/data":"/home/dnalinux/efs/PEPPER/input/data" \
-v "/home/dnalinux/efs/PEPPER/output":"/home/dnalinux/efs/PEPPER/output" \
kishwars/pepper_deepvariant:r0.5 run_pepper_margin_deepvariant call_variant \
-b "/home/dnalinux/efs/PEPPER/input/data/VNS_Yellow_pea.bam" \
-f "/home/dnalinux/efs/PEPPER/input/data/Pisum_sativum_v1a.fa" \
-o "/home/dnalinux/efs/PEPPER/output" \
-p "VNS_Yellow_Pea_PEPPER_Margin_DeepVarian" \
-t 32 \
-r chr4LG4 \ 
--ont
```

**Comment by kishwarshafin** [comment]
@sbassi , I just released r0.6, I think and hope that this will have your issue fixed.
