### ISSUE TITLE
Optional step - getting haplotagged BAM and phased VCF

### ISSUE THREAD

**Issue by ghost** [kishwarshafin/pepper#105]
I am looking to generate a final haplotagged BAM together with a phased VCF file after my PEPPER-Margin-DeepVariant run. 

Is it as simple as no longer using `-M` flag with `margin phase` in the optional step or do I need to run it separately with **allParams.ccs_haplotag.json**? If I understand correctly, this is a different params file used by Margin in the interim step to generated a haplotagged bam file for DeepVariant.

Working with PacBio HiFi reads.

Thanks!
Pierre

**Comment by tpesout** [comment]
Hi Pierre,

The `-M` and `-V` flag just mean "don't output the BAM" and "don't output the VCF"; by default margin writes both.  We've found that for haplotagging we can get an improvement by fine-tuning the params file (hence the "ont_haplotag" and "ccs_haplotag"), but there was not a big difference between the platforms when phasing the VCF.  There is a "phase_vcf" params in that same folder that should be used for this.

Good luck!

**Comment by ghost** [comment]
Thank you Trevor.

Do you recommend to just stick with the "phase_vcf" params in the optional step if `-M` is not used to get a final haplotagged BAM and phased VCF?

**Comment by tpesout** [comment]
I'm not entirely sure what you mean, but after the final DeepVariant run to get the genotyped variants, you can phase them with margin using the "phase_vcf" parameters and the `-M` argument.  Using `-M` just saves runtime, as it won't attempt to write the haplotagged bam, and there's no use for it after the final DV step.

`margin phase BAM REF VCF params/misc/allParams.phase_vcf.json -t THREADS -o OUTPUT_PREFIX -M`

**Comment by ghost** [comment]
Apologies, I was not entirely clear originally. I was thinking of discarding the interim haplotagged BAM file and generating a new one together with a phased VCF based on my final DeepVariant run for manual review of different calls.

**Comment by tpesout** [comment]
Ahh, yes, in that case leave out the `-M` parameter and you'll get the haplotagging information from the final set of calls.

**Comment by kishwarshafin** [comment]
@aronnaxuk , I'll close this issue, please feel free to re-open if you have any more queries.
