### ISSUE TITLE
guppy 5 hac model

### ISSUE THREAD

**Issue by rrazaghi** [kishwarshafin/pepper#106]
Hi Kishwar,

Was wondering if I could use guppy 5 hac model calls with the latest version or I should re-basecall with sup model.

Best,
Roham

**Comment by kishwarshafin** [comment]
hi @rrazaghi , sorry for the delay in response. At this moment it's best to use `guppy 5.0.7 sup` reads as it provides the best results. We don't generate the `hac` reads internally anymore so we will not be generating `hac` models. The benefit you get with `sup` surpasses the long runtime you have for basecalling. Hope you understand.
