### ISSUE TITLE
Follow up on #101

### ISSUE THREAD

**Issue by SHuang-Broad** [kishwarshafin/pepper#107]
Sorry for reposting, but I cannot seem to be able to re-open that particular ticket.

https://github.com/kishwarshafin/pepper/issues/101#issuecomment-945040846

**Comment by kishwarshafin** [comment]
@SHuang-Broad , I'll get back to you on this very soon. Sorry for the delay.

**Comment by SHuang-Broad** [comment]
Hi  @kishwarshafin and @tpesout, just checking in to see if there's an update on this.
Thanks!
Steve

**Comment by tpesout** [comment]
Hi @SHuang-Broad, I replied back on the original thread.  Sorry for the delay!

**Comment by SHuang-Broad** [comment]
Replied there. 
Will post a formal update here once I run with the suggested update.
Thanks!

**Comment by SHuang-Broad** [comment]
It's working, with one catch: the return code doesn't seem to be zero.

I tried the suggested change for Cromwell.

```bash
set -euxo pipefail
mkdir -p "/cromwell_root/margin_output"
...
margin phase \
  ~{bam} \
  ~{ref_fasta} \
  ~{unphased_vcf} \
  /opt/margin_dir/params/misc/allParams.phase_vcf.json \
  -t "${num_core}" \
  -M \
  -o "~{output_root}/~{prefix}" \
  2>&1 | tee "~{output_root}/logs/5_margin_phase_vcf.log" || echo "margin has non-zero return status"

bgzip -c "~{output_root}/~{prefix}".phased.vcf > "~{output_root}/~{prefix}".phased.vcf.gz && \
  tabix -p vcf "~{output_root}/~{prefix}".phased.vcf.gz
```

And I see the `echo` command run, which indicates the return code isn't executed.
```
...
> Starting merge
> Merging results from 30191 chunks.
> Merging took 20s
> Merge cleanup took 0s
> Writing phased VCF to /cromwell_root/margin_output/HG00514.pepper.phased.vcf, phaseset info to /cromwell_root/margin_output/HG00514.pepper.phaseset.bed
[W::hts_idx_load2] The index file is older than the data file: /cromwell_root/broad-dsde-methods-long-reads-outgoing/aou-long-reads-pacbio/PBCCSWholeGenome/HG00514/variants/small/HG00514.deepvariant_pepper.deepvariant_pepper.vcf.gz.tbi
Wrote 6344736 variants: 2130681 were phased; skipped 4076390 for not being analyzed, 137567 for being homozygous, 98 for disagreement with margin
Identified 30772 phase sets with lengths avg:63230, min:0, max:2573535, N50:235991
> Wrote phased VCF in 56s
> Finished phasing in 1h 18m.
margin has non-zero return status
+ echo 'margin has non-zero return status'
+ bgzip -c /cromwell_root/margin_output/HG00514.pepper.phased.vcf
+ tabix -p vcf /cromwell_root/margin_output/HG00514.pepper.phased.vcf.gz
2021/11/03 17:46:56 Starting delocalization.
...
```

More evidence on that is I have bgzip command after the margin command (without that echo), and it ended up not being run when I didn't put in the dummy `echo`, indicating the margin command finished, but the return code was non-zero.

**Comment by SHuang-Broad** [comment]
I do see the following when margin is started, which could be the cause of the non-zero code

```
+ tee /cromwell_root/margin_output/logs/5_margin_phase_vcf.log
tee: /cromwell_root/margin_output/logs/5_margin_phase_vcf.log: No such file or directory
Running OpenMP with 64 threads.
```

**Comment by tpesout** [comment]
Ahh, ya that sounds right.  The "finished phasing" log message indicates that everything worked for margin.

I think if you add a call to `mkdir ~{outputRoot}/logs` or change the margin invocation to `tee ~{outputRoot}/5_margin_phase_vcf.log` it should solve your problem.

**Comment by SHuang-Broad** [comment]
I see.
I'd go with the explicit-dir-creation approach.

Also I'm closing as this is solved.
Thanks @tpesout  and @kishwarshafin !
Steve
