### ISSUE TITLE
Intermediate bam size

### ISSUE THREAD

**Issue by ghost** [kishwarshafin/pepper#108]
Everything works great, however, I just noticed that all of my interim haplotagged bams are consistently a few gigabytes smaller then the original files. Is this  an expected behaviour? 

Working with pacbio HiFi reads.

Thanks!
Pierre

**Comment by kishwarshafin** [comment]
Hi Pierre,

Yes, that is expected as Margin only keeps the primary reads and removes all secondary and supplementary reads from the bam file. So you should expect a slightly smaller bam file.
