### ISSUE TITLE
Getting GVCF after variant_call completed

### ISSUE THREAD

**Issue by GuillaumeHolley** [kishwarshafin/pepper#109]
Hi,

I completed a run of Pepper-MARGIN r0.4 on one of my sample and realized afterwards that I forgot to request the GVCF in output. Since I still have the intermediate files, including the haplotagged BAM file, would it be possible to re-start Pepper-MARGIN "halfway" to get the GVCF or do I have to recompute everything from scratch?

Thank you.
Guillaume

**Comment by kishwarshafin** [comment]
@GuillaumeHolley , you can only run deepvariant on it, do you have the logs? It should have the DeepVariant command in it, if you run DeepVariant with that command with the docker with --gvcf option, you should be able to generate the gvcf.

**Comment by GuillaumeHolley** [comment]
Worked like a charm @kishwarshafin, thanks for the tip!
