### ISSUE TITLE
Bug in pepper_deepvariant:r0.6 docker run_pepper_margin_deepvariant.py

### ISSUE THREAD

**Issue by jdemeul** [kishwarshafin/pepper#110]
Hi @kishwarshafin,

Thanks again for this awesome toolkit.
I've run into an issue with the r0.6 PEPPER_DeepVariant docker, which I think may just be a typo on line 238 of `/usr/local/lib/python3.8/dist-packages/run_pepper_margin_deepvariant/run_pepper_margin_deepvariant.py` in the container.

When you construct the `margin phase` command, the bam is added twice, once correctly, but the second time instead of the reference fasta, resulting in the command and error below:

```
[11-05-2021 13:02:15] INFO: [8/9] RUNNING THE FOLLOWING COMMAND
-------
time margin phase ./PHASED.PEPPER_MARGIN.haplotagged.bam ./PHASED.PEPPER_MARGIN.haplotagged.bam ./PEPPER_MARGIN_DEEPVARIANT_OUTPUT.vcf.gz /opt/margin_dir/params/phase/allParams.phase_vcf.ont.json -t 36 -o ./DEEPVARIANT_OUTPUT 2>&1 | tee ./logs/6_margin_phase.log;
bgzip ./DEEPVARIANT_OUTPUT.phased.vcf;
tabix -p vcf ./DEEPVARIANT_OUTPUT.phased.vcf.gz
-------
Running OpenMP with 36 threads.
> Parsing model parameters from file: /opt/margin_dir/params/phase/allParams.phase_vcf.ont.json
> Parsed 155793 total VCF entries from ./PEPPER_MARGIN_DEEPVARIANT_OUTPUT.vcf.gz; kept 63751 HETs, skipped 0 for region, 48009 for not being PASS, 44033 for being homozygous, 0 for being INDEL
> Set up bam chunker in 3s with chunk size 100000 and overlap 10000 (for region=chr20), resulting in 663 total chunks
> Ordering chunks by estimated depth
> Setup complete, beginning run
> Polishing  4% complete (31/663, 0s).  Estimated time remaining: unknown
[E::fai_build_core] Format error, unexpected "B" at line 1
[faidx] Could not load fai index of ./PHASED.PEPPER_MARGIN.haplotagged.bam
```

For completeness, I'm invoking the variant calling workflow as follows:
```
run_pepper_margin_deepvariant call_variant \
            -b $sorted_bam \
            -f $genomeref \
            -o . \
            -p ${params.sampleid} \
            -s ${params.sampleid} \
            -t 36 \
            --ont_r9_guppy5_sup \
            --phased_output
```

PS: line 140 
```
margin_command = margin_command + "mv " + options.output_dir + "/*.bam " + options.output_dir + "/PHASED.PEPPER_MARGIN.haplotagged.bam; \n"
```
is also a source of non-zero exit statuses for the script, where either `mv` complains that source and target are the same or that the target is not a directory (when providing, respectively `-o somefolder` or `-o .`, in the `run_pepper_margin_deepvariant` command as above)

**Comment by kishwarshafin** [comment]
@jdemeul Confirming that I've seen this and trying to replicate the error internally. It somehow passes our internal test but I see the error you caught, give me about an hour to figure out what exactly happened.

**Comment by kishwarshafin** [comment]
@jdemeul , confirming that the error actually is there, I'm fixing it now.

**Comment by kishwarshafin** [comment]
@jdemeul , I have pushed a new docker. Please do a `docker pull` and the digest should match this:
```bash
r0.6: Pulling from kishwars/pepper_deepvariant
Digest: sha256:3d1b376abbad275c884c0f96dc2784c0446f055ab9e8afda446ed7dd32d79e51
```
If you run the same command again, you should see it running smoothly. Thank you for reporting the issue!

**Comment by jdemeul** [comment]
Thanks @kishwarshafin , I can confirm the new image works like a charm!
