### ISSUE TITLE
If other BAMs are in output folder, `run_pepper_margin_deepvariant` fails.

### ISSUE THREAD

**Issue by williamrowell** [kishwarshafin/pepper#111]
I was integrating the commands from the [HiFi Variant Calling with Singularity case study](https://github.com/kishwarshafin/pepper/blob/r0.6/docs/pipeline_singularity/HiFi_variant_calling_singularity.md#step-3-run-pepper-margin-to-generate-a-phased-bam) into a benchmarking snakemake, and the jobs kept failing after the Margin step with an error about `mv`.  I launched a manual `--dry` run and saw that the command below was the problem.

```
mv ./*.bam ./PHASED.PEPPER_MARGIN.haplotagged.bam;
```

Because I was storing the input (a temporary merged aBAM) in the same directory, the wildcard was expanding to multiple files and causing this step to fail.

You know the exact name of the BAM that you want to move at this stage, right?  Is the wildcard necessary?

**Comment by kishwarshafin** [comment]
hi @williamrowell ,

Thanks for pointing out the issue. You are right, all of the wildcards are removable now, they were set because everything was so wildly changing during development that the iteration process became too difficult. I'll fix this first thing tomorrow.

**Comment by williamrowell** [comment]
Thanks!  From what I've seen so far, p-m-dv is really impressive.

**Comment by kishwarshafin** [comment]
@williamrowell , thank you! I have now pushed a new docker with the following credentials:

```
r0.6: Pulling from kishwars/pepper_deepvariant
Digest: sha256:42b061fb830c522d3b8fa972558c8f4114d43f5c869e98f595eeb776af79b62c
Status: Image is up to date for kishwars/pepper_deepvariant:r0.6
docker.io/kishwars/pepper_deepvariant:r0.6
```
This has all of the wildcard move commands removed so you should have your issue fixed.

**Comment by williamrowell** [comment]
Thanks, that sounds great.
