### ISSUE TITLE
prefix

### ISSUE THREAD

**Issue by husamia** [kishwarshafin/pepper#113]
The option --output_prefix -p doesn't seem to work. all the files generated have the same name.

**Comment by kishwarshafin** [comment]
@husamia ,

Yes, I mistakenly dropped the function call that utilizes `-p`, I'll fix it in the next push.

**Comment by kishwarshafin** [comment]
@husamia , 

I've fixed this issue on `r0.7` please do a pull and try it out. If you see the error persists, please feel free to reopen the issue.
