### ISSUE TITLE
How to obtain TRUTN_BAM_H1 and TRUTH_BAM_H2.

### ISSUE THREAD

**Issue by minghuaxu** [kishwarshafin/pepper#114]
Hi

Thank you for developing PEPPER.

 I encountered some problems while training PEPPER-SNP.

I don‘t konw how to obtain the `TRUTH_BAM_H1` and `TRUTH_BAM_H2` when running `pepper_snp_train make_train_images`.

how do I get the `truth_hp1` and `truth_hp2` using reference genome and variant dataset.This question is more important to me, because I want to use HG001's relevant data to train the model.

The file I need just like this.

<img width="278" alt="like this" src="https://user-images.githubusercontent.com/36125399/145131093-9ede02aa-c66e-41c4-b532-9edd0de62b12.png">

Thanks

Minghua

**Comment by kishwarshafin** [comment]
@minghuaxu ,

We will have a full case study on how to train PEPPER in the next release. It'd be great if you could wait until next week.

**Comment by minghuaxu** [comment]
@kishwarshafin ,

Thanks, I'm looking forward to it!
