### ISSUE TITLE
error messages for incomplete deepvariant-run on HPC.

### ISSUE THREAD

**Issue by myonaung** [kishwarshafin/pepper#115]
<img width="1368" alt="error_message_deepvariant" src="https://user-images.githubusercontent.com/30123717/145916840-6cd9082c-6dc4-4bc3-b593-57ea51a9c47d.png">

**Comment by kishwarshafin** [comment]
@myonaung ,

Can you please run the following command on your machine and post the output here:
`lscpu`

**Comment by myonaung** [comment]
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
Stepping:              4
CPU MHz:               2799.957
CPU max MHz:           3700.0000
CPU min MHz:           1000.0000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              22528K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear spec_ctrl intel_stibp flush_l1d

**Comment by kishwarshafin** [comment]
@myonaung , thank you, can you please give me the command you are running so I can replicate the issue internally?

**Comment by myonaung** [comment]
@kishwarshafin , thanks for prompt responses. It is as follows:


```
module load gcc/8.3.0 singularity/3.6.3

BASE="path-to-data"

# Set up input data
INPUT_DIR="${BASE}/input/data"
REF="GRCh38_no_alt.chr20.fa"
BAM="HG002_guppy_507_2_GRCh38_pass.chr20.30x.bam"

# Set the number of CPUs to use
THREADS="2"

# Set up output directory
OUTPUT_DIR="${BASE}/output"
OUTPUT_PREFIX="HG002_ONT_30x_2_GRCh38_PEPPER_Margin_DeepVariant.chr20"
OUTPUT_VCF="PEPPER_MARGIN_DEEPVARIANT__OUTPUT.vcf.gz"

## Create local directory structure
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${INPUT_DIR}"

# Download the data to input directory
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/usecase_data/HG002_guppy_507_2_GRCh38_pass.chr20.30x.bam
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/usecase_data/HG002_guppy_507_2_GRCh38_pass.chr20.30x.bam.bai
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/usecase_data/GRCh38_no_alt.chr20.fa
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/usecase_data/GRCh38_no_alt.chr20.fa.fai



singularity exec --bind path-to-project-on-HPC/pepper-deepvariant/  pepper_deepvariant_r0.6.sif run_pepper_margin_deepvariant call_variant -b "${BASE}/${BAM}" -f "${BASE}/${REF}" -o "${OUTPUT_DIR}" -p "${OUTPUT_PREFIX}" -t ${THREADS} --ont_r9_guppy5_sup 
```

**Comment by kishwarshafin** [comment]
@myonaung,

I pushed a test `r0.7` docker that has qunatization off by default. You can access it by doing:
```
singularity pull docker://kishwars/pepper_deepvariant:test-r0.7
```

And then run:
```
singularity exec --bind path-to-project-on-HPC/pepper-deepvariant/  pepper_deepvariant_test-r0.7.sif run_pepper_margin_deepvariant call_variant -b "${BASE}/${BAM}" -f "${BASE}/${REF}" -o "${OUTPUT_DIR}" -p "${OUTPUT_PREFIX}" -t ${THREADS} --ont_r9_guppy5_sup 
```

Can you please run this an see if the error still appears?

**Comment by myonaung** [comment]
Thanks for the fix. I think the error is gone. Do I need to change something in the result interpretation with this pepper_deepvariant_test-r0.7.sif ?

**Comment by kishwarshafin** [comment]
@myonaung , nope, r0.7 is more accurate. We are hoping to officially release it next week. 

It would be very helpful if you please close the two issues you created.
