### ISSUE TITLE
explanation on intermediate files

### ISSUE THREAD

**Issue by myonaung** [kishwarshafin/pepper#117]
Hi, Just wondering where can I find explanation to intermediate files ? I couldn't find it on the original manuscript.

**Comment by kishwarshafin** [comment]
@myonaung ,

Thanks for opening this issue. So far, we have not written any documentation on which file represents what stage of the pipeline. It'll take a little bit of time to get there. In the meantime, are you looking for anything specific? The overall pipeline is the same as we described in the manuscript.

**Comment by myonaung** [comment]
@kishwarshafin,

I am just wondering what is the difference between PEPPER_HP_VARIANT_FULL.vcf.g vs PEPPER_VARIANT_OUTPUT_VARIANT_CALLING.vcf.gz.

**Comment by kishwarshafin** [comment]
@myonaung ,

We have these two parameters:
You can handle this by using these two parameters:
```bash
--pepper_snp_q_cutoff 15
--pepper_indel_q_cuoff 10
```
Any candidate variant that has quality value lower than these set threshold are re-genotyped with DeepVariant. `PEPPER_HP_VARIANT_FULL.vcf.gz` contains all of the candidate variants that PEPPER found.
`PEPPER_VARIANT_OUTPUT_VARIANT_CALLING.vcf.gz` are candidates that are low-quality from PEPPER and needs to be re-genotyped with DeepVariant. After re-genotyping, we combine the variants together.

**Comment by kishwarshafin** [comment]
@myonaung , You can now read how the method works here: https://github.com/kishwarshafin/pepper/blob/r0.7/docs/misc/pepper_v0.7_method_update.md

Please reopen this issue if you have more questions.

**Comment by myonaung** [comment]
Thanks, very detail explanations. Just wondering if you use mutliple bams as input ? Something similar to Freebayes multiple bams input for gvcf generation ?
