### ISSUE TITLE
r0.7 for Guppy4 data

### ISSUE THREAD

**Issue by aquaskyline** [kishwarshafin/pepper#118]
Hi, thanks for the great tool. I have a plant sample on which I am ensembling the variant calls by PEPPER and Clair3. Unfortunately, I only have Guppy4 basecalled reads for the sample and I lost the fast5s in a failed portable harddrive. It seems the newest version that supports Guppy4 data is r0.4. Will r0.7 or a later version also support Guppy4 data?

**Comment by kishwarshafin** [comment]
Hello, thank you for opening this issue. I will bring this issue up in our next group meeting. We do plan to support the hac model, but not sure if it will be specific to guppy4.

**Comment by aquaskyline** [comment]
Thanks for discussing it. Having a Guppy 4 model for PEPPER r0.7 also helps me to come up with a new benchmark between PEPPER r0.7 and Clair3 on Guppy 4 data.

**Comment by felixm3** [comment]
Hi Kishwar,

I'd also like to use PEPPER-Margin-DeepVariant and have a similar question. 

Does `--ont_r9_guppy5_sup` work for:
- all r9 pores (9.4, 9.4.1, etc)?
- all Guppy versions up to 5 i.e. Guppy 3, Guppy 4, etc?
- MinION vs PromethION?
- Basecalling modes other than sup i.e. fast and hac?

Thanks!

**Comment by kishwarshafin** [comment]
@felixm3 ,

`--ont_r9_guppy5_sup` works for all `r9.4.1` pores basecalled with `guppy 5+ "sup" mode` on any platform. So the version of your basecaller has to be `guppy 5` or higher and use "SUP" mode and not the HAC mode.


Also, a sidenote, we are currently talking to the HPRC production group to see if all HPRC calls can be re-basecalled with `guppy5+ sup` basecaller. Re-visiting previous basecaller models is not an ideal scenario as we are working on expanding the applications of our methods.

**Comment by felixm3** [comment]
Thanks for the response Kishwar.

Just to make sure I've understood, currently `--ont_r9_guppy5_sup`:
- only strictly works for `r9.4.1` pores and NOT `r9`, `r9.4` or `r9.5`
- only strictly works for `sup` mode and NOT `fast` or `hac` mode

Is this correct?

**Comment by kishwarshafin** [comment]
Ah, sorry, yeah, too many variations:

* It will work on *any* r9 pore, which means `r9`, `r9.4` and `r9.5`.
* It will *only* work on `sup` mode and not `fast` and `hac` mode. 

We define `the model works` = `the model has been tested, verified, and benchmarked` before deployment on these datatypes. You can always run the model on the other data modalities to see if it gives you a good set of variants or not.

**Comment by felixm3** [comment]
Got it!

Thanks!
