### ISSUE TITLE
Can PEPPER-Margin-DeepVariant used in nanopore RNA-seq?

### ISSUE THREAD

**Issue by chilampoon** [kishwarshafin/pepper#119]
Hi there, I wonder if the PEPPER-Margin-DeepVariant pipeline can work well on RNA variant calling or not? 
DeepVariant doesn't have an RNA seq model but users may try the exome model... https://github.com/google/deepvariant/issues/115

**Comment by kishwarshafin** [comment]
Hi @chilampoon ,

This is a very interesting question. We have not evaluated PEPPER-Margin-DeepVariant on RNA-seq data but an independent investigation did use PEPPER-Margin-DeepVariant on RNA-seq data and noted: "achieved 98.3%
recall and 95.9% precision": https://www.biorxiv.org/content/10.1101/2021.10.30.466545v1 

The difference in performance could come from the difference in sequencing data which is not done with ONT library prep and basecalling. Outside this, we don't have any model to point to that can be interesting for you. If you try our method and do not see sensible results, then please open an issue with specific cases and we will do our best to support your use case.

**Comment by chilampoon** [comment]
Hi @kishwarshafin thanks for the info! I noticed that the variant calling evaluation was on germline variants, what about those somatic mutations? seems like DeepVariant is only for germline variant calling?

**Comment by kishwarshafin** [comment]
@chilampoon ,

That is correct. As we don't have a way to benchmark or train somatic variants, we don't have a model for somatic calling. Furthermore, the method can't handle clonality at this moment. If you use it for somatic calling then clonality needs to be considered separately.
