### ISSUE TITLE
Bring in updates made in DV v1.3.0

### ISSUE THREAD

**Issue by SHuang-Broad** [kishwarshafin/pepper#120]
I can confirm that the log output from DV, when using 1.3.0, is significantly less (1MB vs 500MB).
So it would be nice if DV-Pepper can bring that change it and make a release from that as well.

Thank you!
Steve

**Comment by kishwarshafin** [comment]
hi @SHuang-Broad ,

Thank you, I'll note this as a to-do. I'll notify you once you are done running all the tests with the new version.

**Comment by kishwarshafin** [comment]
Hello @SHuang-Broad ,

The `r0.8` has DeepVariant 1.3.0 incorporated.
