### ISSUE TITLE
Multiple bams

### ISSUE THREAD

**Issue by myonaung** [kishwarshafin/pepper#122]
Thanks, very detail explanations. Just wondering if you use mutliple bams as input ? Something similar to Freebayes multiple bams input for gvcf generation ?

_Originally posted by @myonaung in https://github.com/kishwarshafin/pepper/issues/117#issuecomment-1006259834_

**Comment by kishwarshafin** [comment]
@myonaung ,

No, currently we don't support multi-sample variant calling. It is expected that the input bam file contains sequences from only one sample. Currently, you will need to split the bam into multiple bams where each bam contains sequences from one sample and then call variants. You can finally merge the variant call files to generate a multi-sample VCF. 

Supporting multi-sample calling would require major refactoring in PEPPER-Margin's codebase. Although DeepVariant supports it, we can't utilize it immediately.
