### ISSUE TITLE
Problems about “UserWarning”

### ISSUE THREAD

**Issue by LiShuhang-gif** [kishwarshafin/pepper#126]
Hi, I have tried to use PEPPER to detect SNPs based on ONT data. However, when I check the log files, I've found some warning messages (instead of error messages, I think) as follows:

```
(base) [shali@vm-login01 PEPPER_snp_calling]$ less PEPPER_17HanZZ0019.log | grep -i error
/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_opset9.py:2095: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_opset9.py:2095: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
```

I did get a vcf.gz file, and there is no other "error" information in the log file. I wonder if the program works correctly, even with this warning message?  In other words, did this warning message affect the correctness of the results?
Thanks!

**Comment by kishwarshafin** [comment]
@LiShuhang-gif , you can ignore the error message, it's just saying to be careful while converting models. Warnings have no effect on the output.
