### ISSUE TITLE
typo in your installation instructions

### ISSUE THREAD

**Issue by rainwala** [kishwarshafin/pepper#127]
Hi,

On this page:
https://github.com/kishwarshafin/pepper/blob/r0.7/docs/local_install/install_pepper_locally.md

you have mispelled "venv" as "vnev" in this command:
`. ./vnev/bin/activate`

Please change it, as some people may not figure it out  :)

**Comment by kishwarshafin** [comment]
Thank you @rainwala, I'm making a few changes to the program, will update this with others very soon.

**Comment by kishwarshafin** [comment]
Hi @rainwala , 

I have fixed this in the new release.
