### ISSUE TITLE
Bacteria

### ISSUE THREAD

**Issue by joergFLI** [kishwarshafin/pepper#128]
Hi,
looks like an interesting tool. Would be possible to use with bacterial data, even with fragmented reference genomes?
Thanks

**Comment by kishwarshafin** [comment]
Hello, 

In terms of bacterial application, we do not have any benchmark that we can provide as there is no microbial variant benchmarking available. 

On the other hand, we have applied our pipeline on CHM13 which is effectively haploid to get a very good set of results. You can definitely use the pipeline to see if it's suitable for you.
