### ISSUE TITLE
Stitch module error

### ISSUE THREAD

**Issue by reachsagaya** [kishwarshafin/pepper#131]
Hi,
I am having issue running the  'python3 -m pepper.pepper stitch -i .../my_predictions -o ../my_output'
This is the error Iam getting:

> File "/share/rwmwork/Sagaya/Packages/anaconda3_2021/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/rwmwork/Sagaya/Packages/anaconda3_2021/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/rwmwork/Sagaya/Packages/anaconda3_2021/lib/python3.9/site-packages/pepper/pepper.py", line 427, in <module>
    main()
  File "/share/rwmwork/Sagaya/Packages/anaconda3_2021/lib/python3.9/site-packages/pepper/pepper.py", line 399, in main
    perform_stitch(FLAGS.input_dir,
  File "/share/rwmwork/Sagaya/Packages/anaconda3_2021/lib/python3.9/site-packages/pepper/modules/python/perform_stitch.py", line 44, in perform_stitch
    with h5py.File(prediction_file, 'r') as hdf5_file:
  File "/share/rwmwork/Sagaya/Packages/anaconda3_2021/lib/python3.9/site-packages/h5py/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/share/rwmwork/Sagaya/Packages/anaconda3_2021/lib/python3.9/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

Please let me know how to fix this, or is it due to the recent updates in the sofware.

Thanks in advance.

**Comment by kishwarshafin** [comment]
@reachsagaya ,

Are you polishing your genome with PEPPER? This independent polishing module is not supported anymore. Can you please explain your use-case so I can help better?

**Comment by reachsagaya** [comment]
Dear Kishwar,
Thanks for the quick resposnse.
I have used  the pepper polish module previously to polish an ONT assembly I had generated using Shasta assembler, and the results were fantastic.  
Now Iam trying to do the same for another assmebly, but not able to run the pepper polish or pepper stitch command, eventhough the predictions and consensus are complete.  Please let me know how to get pepper polish working again.
Thanks

**Comment by kishwarshafin** [comment]
@reachsagaya , 

We have updated the polishing pipeline to include DeepVariant which produces much better results. You can follow the command from here:
https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_docker/ONT_polishing.md

What is the basecaller version that you are using?

**Comment by reachsagaya** [comment]
Iam using the Guppy 5.0.1 basecaller.
Is there a document to run this without docker, do a local install of everything?, as our system does not support docker.

**Comment by kishwarshafin** [comment]
@reachsagaya yes, you can use singularity: https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_singularity/ONT_polishing_singularity.md

Also, are these "SUP" reads?

**Comment by reachsagaya** [comment]
Thanks for your help.  Please close this issue.

**Comment by reachsagaya** [comment]
Hi Kishwar,

Sorry to reopen this issue again:  Iam using PEPPER to polish my ONT assembly using the SUP reads and unfortunately the pipeline generated HAP1.vcf and HAP2.vcf but have not produced the POLISHED_ASM_HAP1 or POLISHED_ASM_HAP2.  Here is the code Iam using, could you please let me know if something is not correct?

`singularity exec --bind /usr/lib/locale/ -H /04-Polish/G5/Pepper_mod $PEPPER_IMG_PATH/pepper_deepvariant-r0.4.simg run_pepper_margin_deepvariant polish_assembly \
 -b draft_polish_ArSer.sort.bam \
 -f Assembly.fasta \
 -o /04-Polish/G5/Pepper_mod/pep_mod_output_try1/ \
 -t 42 \
-s ArSer_Run01re_02_G5 \
--ont
`

**Comment by kishwarshafin** [comment]
@reachsagaya ,

The last step is to run `bcftools consensus` too apply the variants back to the assembly.
