### ISSUE TITLE
Support for Conda / local without admin rights

### ISSUE THREAD

**Issue by tuannguyen8390** [kishwarshafin/pepper#132]
Hi there,

I put an issue up to see if dev has any plan to deploy PEPPER to conda or any platform that doesn't require admin rights for installation. My local HPC does not grant admin rights for users nor provide installation of Docker.

Many thanks,

Tuan

**Comment by kishwarshafin** [comment]
@tuannguyen8390 ,

You can use singularity to run our pipelines. See here: https://github.com/kishwarshafin/pepper/blob/r0.7/docs/quickstart/variant_calling_singularity_quickstart.md
