### ISSUE TITLE
sm_86 support in r0.7-gpu docker

### ISSUE THREAD

**Issue by fellen31** [kishwarshafin/pepper#134]
Hi, 

seems like support for sm_86 might be missing in the `r0.7-gpu` docker?

Things are working fine with `r0.5-gpu` as confirmed in https://github.com/kishwarshafin/pepper/issues/71#issuecomment-912114735. 

Thanks!

**Comment by kishwarshafin** [comment]
@fellen31 ,

I'm working on it, should be fixed soon.

**Comment by kishwarshafin** [comment]
Hi @fellen31 ,

This should be fixed in `r0.8-gpu` version. Please reopen if you don't see it fixed.
