### ISSUE TITLE
polish_assembly deprecated? How to get two haplotype assembly files?

### ISSUE THREAD

**Issue by dithiii** [kishwarshafin/pepper#136]
My dataset is ONT deep sequencing of a single diploid individual. I successfully ran the call_variants version of pepper-margin-deepvariant, which generated a nice haplotagged bam file and phased vcf.gz. However I was hoping to generate separate assemblies for each haplotype, e.g. hap1.fasta and hap2.fasta. My goal is to assemble, polish, and phase a diploid genome for submission to NCBI as a _diploid_ reference sequence (which to my understanding, requires separate assemblies for each haplotype). 

I see that pepper-margin-deepvariant (used to?) have this functionality in 'polish_assembly' but it doesn't appear to exist in 0.7-gpu version. I got the following error:
`run_pepper_margin_deepvariant: error: argument sub_command: invalid choice: 'polish_assembly' (choose from 'call_variant')`

**Comment by kishwarshafin** [comment]
Hi @dithiii ,

We recommend using hapdup (https://github.com/fenderglass/hapdup) for diploid polishing for now. The PEPPER-Margin-DeepVariant polishing pipeline couldn't handle large SVs. Even though the base-level quality was good, we were missing many SVs that differentiate between two haplotypes. So for now, we suggest using hapdup. Thank you for opening this issue, I'll mention this on the landing page from the next release.

**Comment by kishwarshafin** [comment]
@dithiii , 

I'm closing this for now, please reopen if you have more questions.
