### ISSUE TITLE
variants are not called by run_pepper_margin_deepvariant

### ISSUE THREAD

**Issue by Josephhungyi** [kishwarshafin/pepper#137]
Hello,

I used r0.5 version and my reference to get variants. I obviously saw the variant on IGV, but I couldn't see the variant on vcf. Any suggestion to improve it. Thanks
![1646991931205](https://user-images.githubusercontent.com/61561578/158296673-9c0ee27e-7c43-492f-8441-af3470b50ab9.jpeg)

**Comment by kishwarshafin** [comment]
@Josephhungyi ,

Can you please provide a little more information? What is the guppy basecaller version? Is this human genome? Is there a good strand separation for the variants?

**Comment by Josephhungyi** [comment]
Hello @kishwarshafin,

The guppy version is 5.0.13. My reference is human genome, but there are repeat units in this region. My goal is to get all SNP or haplotypes. For other samples, the variants can be called properly in the same region. 

Thanks

**Comment by kishwarshafin** [comment]
@Josephhungyi , if you are using "sup" basecaller then please switch to r0.7, this release has 3x fewer errors compared to r0.5.

**Comment by Josephhungyi** [comment]
Hello @kishwarshafin ,

I tried r0.7 with default, but the variant hasn't been called. Any suggestion?

Thanks

**Comment by kishwarshafin** [comment]
OK, in that case, I'd ask if you can see the variant in the candidate set. Can you please see if the variant is present in: `intermediate_files/PEPPER_VARIANT_FULL.vcf.gz`. You can do that by running: `bcftools view PEPPER_VARIANT_FULL.vcf.gz contig_name:start_pos:end_pos`

**Comment by kishwarshafin** [comment]
@Josephhungyi , is this amplicon sequencing? I see that the cover is ranging at 3000ish?

**Comment by Josephhungyi** [comment]
Hello @kishwarshafin ,

It is amplicon sequencing, and I did not see the variant in vcf.

Thanks

**Comment by kishwarshafin** [comment]
@Josephhungyi , 

For amplicon sequencing, we suggest downsampling the data to a manageable coverage so Margin can phase the reads correctly (See https://github.com/kishwarshafin/pepper/issues/125). 

 Can you please follow these steps:
 1) Downsample the reads using `samtools view -s` to somewhere around 90x-100x.
 2) Run `PMDV-r0.8` on the downsampled bam file (r0.8 was released yesterday).
 3) If the variant is still missing, please look at `intermediate_files/PEPPER_VARIANT_FULL.vcf.gz` to see if the variant is there.
 
 If you don't see the variant, then we need to try some parameters out where we lower the threshold for a variant to be reported. But first, please do the steps mentioned and see if that helps.

**Comment by Josephhungyi** [comment]
@kishwarshafin ,

I appreciate your help. Downsampling is helpful. Another question, I found a missing indel on vcf with r0.8 version and I also downsampled the bam file to 100X. Any suggestion?
![1647501721501](https://user-images.githubusercontent.com/61561578/159407317-8924841b-90e6-4a42-9ac6-dcb2b4d9e4c2.jpeg)

**Comment by kishwarshafin** [comment]
@Josephhungyi ,

I'm closing this issue for now. If you have further questions or queries then please feel free to reopen this issue. Hope the suggestion helped your use case.
