### ISSUE TITLE
Can PEPPER deal with CLR sequencing data?

### ISSUE THREAD

**Issue by LiShuhang-gif** [kishwarshafin/pepper#139]
Hi, I am trying to use PEPPER to detect SNPs based on PacBio CLR sequencing data. However, I found that PEPPER gave only parameters for ONT and HiFi sequencing data.

```
--ont_r9_guppy5_sup

# --ont_r9_guppy5_sup is preset for ONT R9.4.1 Guppy 5 "Sup" basecaller
# for ONT R10.4 Q20 reads: --ont_r10_q20
# for PacBio-HiFi reads: --hifi
```

I just wonder, can PEPPER handle CLR sequencing data? Thanks in and look forward to your reply.

**Comment by LiShuhang-gif** [comment]
Besides, Can PEPPER process ultra-long reads data from Nanopore? If so, what parameters are appropriate?

**Comment by kishwarshafin** [comment]
@LiShuhang-gif ,

1) We currently don't have a CLR SNP calling model in production. 

2) The UL reads show work similarly well as the non-UL reads. In fact, all of the models are trained on UL reads. If you see memory usage issues then please let me know and I'll suggest you parameters.
