### ISSUE TITLE
Can I use deep-trio in the pepper-margin-deepvariant pipeline?

### ISSUE THREAD

**Issue by jessieshen97** [kishwarshafin/pepper#140]
I have noticed you updated deepvariant v1.3.0 in the pipeline, but I don't know if I can use deep-trio which was built on top of deepvariant in the pipline.
If it is possible to merge deep-trio in the pipline? Or is there any methods I can run deep-trio instead of deepvariant?
Thank you!

**Comment by kishwarshafin** [comment]
hi @jessieshen97 ,

We don't have a deeptrio model for ONT in production yet.

**Comment by jessieshen97** [comment]
> 

Thank you. And how about pacbio data?

**Comment by kishwarshafin** [comment]
@jessieshen97 ,

DeepTrio is supported natively with PacBio. You don't need PEPPER-Margin to work with that. You can see the details here: https://github.com/google/deepvariant/blob/r1.3/docs/deeptrio-details.md
