### ISSUE TITLE
Problem with make_image module

### ISSUE THREAD

**Issue by ghost** [kishwarshafin/pepper#141]
Hello!

I want to generate labeled training samples using my own BAM, FASTA and VCF... but the module "pepper_variant make_images" generates the images in a file "hdf5" that contains the following keys: ['candidate_frequency', 'candidates', 'contigs', 'depths', 'images', 'positions']... What should I do to get the labels to train models? The command I am using is the following:

pepper_variant make_images \
    --bam $BAM_FILE_PATH \
    --fasta $REFERENCE_FILE_PATH \
    --output_dir $OUTPUT_DIR \
    --threads $THREADS \
    --ont_r9_guppy5_sup

**Comment by ghost** [comment]
And "pepper_variant_train make_train_images" generates empty "hdf5" files...

**Comment by ghost** [comment]
I think I found the problem... the module "pepper_variant_train make_train_images" does not specify that it is necessary to pass as argument the file "region_bed" to generate labeled images for training...

**Comment by kishwarshafin** [comment]
@daniusparres , Please follow the instructions here: https://github.com/kishwarshafin/pepper/blob/r0.8/docs/training_pepper_margin_deepvariant/how_to_train_pepper.md
