### ISSUE TITLE
PEPPER hifi model training problems

### ISSUE THREAD

**Issue by jessieshen97** [kishwarshafin/pepper#143]
Hi! I am trying to train a PEPPER snp calling model (HIFI data) for other species, and I follow the model training instructions here. https://github.com/kishwarshafin/pepper/blob/r0.8/docs/training_pepper_margin_deepvariant/how_to_train_pepper.md
But I was stuck in Step 4: Train PEPPER. When I run pepper_variant_train train_model, I got error messages.
Here is my command:
![image](https://user-images.githubusercontent.com/46390528/163954386-06ca774f-0e88-41f8-92e8-14c874bf0f1e.png)
And here is my error messages:
![image](https://user-images.githubusercontent.com/46390528/163954517-a4ee2c6a-1db8-4ad2-a25f-473456fdc499.png)
Does the error message mean that I made mistakes in step3 or something else?

BTW, pepper_margin_deepvariant version I used is r0.8.

**Comment by kishwarshafin** [comment]
Hi @jessieshen97 ,

Yes, it looks like the image generation part generated empty set of images. Can you please check the size of the files to make sure that it worked?

**Comment by jessieshen97** [comment]
> Hi @kishwarshafin 

Yes, I finally figured out what happend. Thank you!
But I still got another question, how does pepper deal with non-PAR sex chromosomes? I am trying to train pepper model with a male animal, but I did not find how to demonstrate the ploidy of my training set. Do I need to just discard the non-PAR x and y chromosomes ?
And also I am quite condused that I always got error messages when typing chromosome names (-r commend in the picture) when I was training the model:
![image](https://user-images.githubusercontent.com/46390528/164621348-2a7405ee-d186-47c1-8a51-0293b0687ea0.png)
I have the "-r" as follow:
![image](https://user-images.githubusercontent.com/46390528/164621860-03f86601-c61c-4a02-9840-0421439dd7c1.png)
And I meet with error:
![image](https://user-images.githubusercontent.com/46390528/164621948-72dea36b-567d-4baf-a813-37fd00205724.png)
Is that error related to the sequence of chromosomes?

**Comment by kishwarshafin** [comment]
@jessieshen97 ,

No this is related to the ${TRUTH_BED}. Can you please check to see if all of the lines in the truth bed are valid? As in, they should have "chr_name start_pos end_pos" per line. I think a line in the truth bed file is missing a value.

**Comment by jessieshen97** [comment]
> Thank you @kishwarshafin 
I have checked the bed file, the have "chr_name start_pos end_pos" per line. I generated the bed file with length of every contigs, cuz we do not have the confident region in the species. Therefore, the bed file is like:
![image](https://user-images.githubusercontent.com/46390528/164954570-d789c6a1-1267-4a9e-905b-1ccb68d4b2f8.png)

**Comment by kishwarshafin** [comment]
@jessieshen97 ,

I think a line or two in this bed file is malformed somehow? Maybe a tab got replaced by a space? Can you show me the command that you used to create this bed file? Bed files require tab between columns.

**Comment by jessieshen97** [comment]
@kishwarshafin ,
I used awk command:
awk 'BEGIN{OFS="\t"}{print $1,0,$2}' dm6.fa.fai > dm6.bed
And the content of dm6.fa.fai is:
chr2L	23513712	7	50	51
chr2R	25286936	23984001	50	51
chr3L	28110227	49776683	50	51
chr3R	32079331	78449122	50	51
chr4	1348131	111170046	50	51
$1 is the chromosome name and $2 is the chromosome length.
I think the .bed file is tab-delimited, and the file is attached, please make sure I did not make any mistakes during my checking.
[dm6.bed.txt](https://github.com/kishwarshafin/pepper/files/8551217/dm6.bed.txt)

**Comment by kishwarshafin** [comment]
@jessieshen97 ,

Ok, sorry I was out for a little bit. So the issue is in the parameter. I see you are sending `contigX-contigY` as your parameter for regions and it's failing to parse it. Please set explicit contig names with "comma" like "contigX,contiY" for your `-r` parameter and it should work.

**Comment by splaisan** [comment]
> @jessieshen97 ,
> 
> Ok, sorry I was out for a little bit. So the issue is in the parameter. I see you are sending `contigX-contigY` as your parameter for regions and it's failing to parse it. Please set explicit contig names with "comma" like "contigX,contiY" for your `-r` parameter and it should work.

may be wrong but it looks like the second is missing 'chr' before Y
