### ISSUE TITLE
Running PEPPER_DEEPVARIANT pipeline on aarch64

### ISSUE THREAD

**Issue by CaptainYvel** [kishwarshafin/pepper#144]
Hi,

we are currently running the PEPPER_DEEPVARIANT pipeline using the docker image tagged as r0.4, which works really well on amd64 architecture. We also want to run the pipeline on aarch64 architecture which is currently not possible since all docker images are only available for amd64.

Is it possible to get a docker image for aarch64 architecture or maybe a Dockerfile to build an image for this architecture? Or maybe another solution how to run the pipeline on aarch64?

Thank you and looking forward to your reply.

**Comment by kishwarshafin** [comment]
@CaptainYvel , I am not exactly sure how easy it will be to build an executable for aarch64. Also, have tried singularity with the latest version of PEPPER in aarch64? I will do a quick check to see if we can support aarch64 soon, please let me know if you have get a chance to try singularity.

**Comment by CaptainYvel** [comment]
Hi @kishwarshafin,

we were able to build the executables on our aarch64 environment but they do not include the trained model. Therefore we would like to use a docker image which also contains the trained model.
Is there a way to use the trained model from the current image with the executables that we've built?

Thank you for your help.

**Comment by kishwarshafin** [comment]
@CaptainYvel ,

All dockers contain the models internally. You can copy the DV models by running this:
```bash
OUTPUT_DIR=<set_path_to_a_local_directory>
DV_MODEL_DIR=${OUTPUT_DIR}/dv_models

docker run \
-v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
-u `id -u`:`id -g` \
kishwars/pepper_deepvariant:r0.8 \
cp -r /opt/dv_models/ ${DV_MODEL_DIR}
```
Or you can copy the pepper models by running:
```bash
OUTPUT_DIR=<set_path_to_a_local_directory>
PEPPER_MODEL_DIR=${OUTPUT_DIR}/pepper_models

docker run \
-v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
-u `id -u`:`id -g` \
kishwars/pepper_deepvariant:r0.8 \
cp -r /opt/pepper_models/ ${PEPPER_MODEL_DIR}
```

**Comment by kishwarshafin** [comment]
btw, I highly recommend switching to the latest version and re-basecall the data with a newer Guppy "SUP" model. It makes a huge difference in overall accuracy.

**Comment by CaptainYvel** [comment]
@kishwarshafin 

Thank you for your help. We will try the solution you have provided.
