### ISSUE TITLE
Is there a way to collect more information in the reported .g.vcf?

### ISSUE THREAD

**Issue by RichardCorbett** [kishwarshafin/pepper#145]
Good day,

I am trying to compare the results from Pepper-margin-deepvariant (PMDV) to our illumina somatic calls for a sample.

The illumina somatic variants are derived by running Mutect2 and Strelka2 on 80X (tumour) and 40X (normal) genomes.   

We have the same tumour sequenced to 80X on our promethion and are looking to find the somatic variants.   Currently there are many (roughly 20%) somatic variants that have little to no evidence in the .g.vcf. However, if I search for those variants in the nanopore bam file I can see non-zero read counts of the ALT allele for the great majority of variants that aren't reported in the .g.vcf.  I have yet to do this but perhaps the missing variants can be rescued by search for positions with lower genotype quality as they don't fit the 0/0, 0/1, or 1/1 model.

I understand that PMDV isn't tuned to call somatic variants in tumour samples, but I'm wondering if there is an easy way to dial up the sensitivity so we can call variants down around 20% VAF.      I would expect this to increase the false positive rate significantly, but we may be able to filter many of those out.     Similarly, is there a way to get more information reported in the .g.vcf?  I'm thinking allele counts, or underlying metrics that are generated at run time.

thanks for all the great work!
RIchard

**Comment by kishwarshafin** [comment]
@RichardCorbett , Sorry for the late reply. You can look at the candidates proposed by PEPPER who are located in the intermediate directory. Also, there are several ways to dial up the sensitivity for long reads. I'm not exactly sure how helpful it'll be for Illumina somatic calls though. You can read how to balance speed vs accuracy here: https://github.com/kishwarshafin/pepper/blob/r0.8/docs/usage/speed_and_accuracy.md

**Comment by kishwarshafin** [comment]
Also, you can look at the list of parameters here: https://github.com/kishwarshafin/pepper/blob/r0.8/docs/usage/usage_and_parameters.md.

You can lower each of the parameters that are responsible for candidate finding and filtering.
