### ISSUE TITLE
Quick question about Deep Learning and Varian Calling

### ISSUE THREAD

**Issue by ghost** [kishwarshafin/pepper#146]
Hi, I love the method! But after using it for several weeks I have a doubt... what is the purpose or reason of using Deep Learning for Variant Calling? What do neural networks contribute to this task? Where can I get information about the reason of using Deep Learning in comparison with the classical perspective?

Best regards and thank you very much,

Daniel

**Comment by kishwarshafin** [comment]
Hello @daniusparres ,

There are several papers that you can read, DeepVariant is the "known" first successful attempt of using DNNs for variant calling, you can read the paper from here: https://www.nature.com/articles/nbt.4235.
