### ISSUE TITLE
Running PEPPER-Margin-DeepVariant pipeline on CRISPR/Cas9-mediated-enrichment nanopore data

### ISSUE THREAD

**Issue by nsanchezcollantes** [kishwarshafin/pepper#147]
Hello,

I am using PEPPER-Margin-DeepVariant pipeline in order to phase reads from CRISPR/Cas9-mediated-targeted enrichment nanopore human data with the following code (find image attached).
![Screenshot 2022-05-20 144517](https://user-images.githubusercontent.com/105925009/169530874-68300310-2f8e-4166-86c2-bc5338fe5b1d.png)

It seems to work nicely for some of the target regions, whereas in others I found either of these two problems:
a) The reads mapping in the target regions are removed from the haplotaged BAM file.
b) The reads were not phased (they lack the HP tag)

Is there any option/parameter I can add/change in the code to solve this problem or is it just that the pipeline can not be used for targeted nanopore data? 

I hope you can help me with that. Thank you in advance.

**Comment by nsanchezcollantes** [comment]
Also, regarding the use of `--region` option to specify a region of interest, can it be used to specify more than one target region, so I can add it to my code?

**Comment by kishwarshafin** [comment]
@nsanchezcollantes , can you provide a little more context on:
a) The reads mapping in the target regions are removed from the haplotaged BAM file.

Are you seeing an empty output file from Margin?

**Comment by nsanchezcollantes** [comment]
Sure. I meant in the output from Margin I am losing some coverage (depth) in the targeted regions compared to that of the input BAM file. It is not that the file is empty.

**Comment by kishwarshafin** [comment]
@nsanchezcollantes ,

That is natural. Margin excluded all reads that are not primary and not above certain mapping quality threshold. The reads you are losing are possibly supplementary or secondary alignments. You can easily confirm it by running `samtools -F0x904` on your initial bam to filter only for primary reads.

**Comment by nsanchezcollantes** [comment]
Thanks for the info. Regarding the reads included in the output BAM file but without HP tag, could you recommend any way of being more permissive with the SNPs that are being considered for the phasing? (i.e. include some of the SNPs filtered out to be able to phase more reads)

**Comment by kishwarshafin** [comment]
@nsanchezcollantes ,

In that case I would recommend running Margin (https://github.com/UCSC-nanopore-cgl/margin) separately on the BAM with your final output VCF file. There are a set of parameters you can tweak to be more permissive during phasing.

**Comment by nsanchezcollantes** [comment]
I have just realized that all the SNPs that did not PASS were filtered out because of RefCall (they were HOM_REF), so they are not being considered in the phasing.
However, the VAF for many of these is around 0.5 with considerably high DP. 
Would you have an idea of why this may be happening and how to deal with it?

**Comment by kishwarshafin** [comment]
@nsanchezcollantes ,

Sorry for being late to reply on this. What is your coverage in these cases? Also, a lot of things can affect calling like low mapping quality of reads, low base quality of reads, strand bias or high mismatch rates nearby etc. It's difficult to tell why exactly it's called a HOM-REF without looking at the data.

**Comment by nsanchezcollantes** [comment]
Yes, I think you are right. Probably, it's a matter of base qualities or mismatches nearby. 

Thank you for your help.

I'll close this issue.
