### ISSUE TITLE
Training margin

### ISSUE THREAD

**Issue by luskry** [kishwarshafin/pepper#149]
Hello,

Thanks for the great tool. Are there instructions for training a custom margin model?

Best,

Ryan

**Comment by kishwarshafin** [comment]
@luskry , 

Margin is a HMM-based algorithm. You need to change the parameters, you can set Margin parameters  with `--margin_haplotag_model` and `--margin_phase_model` described here: https://github.com/kishwarshafin/pepper/blob/r0.8/docs/usage/usage_and_parameters.md.

The parameters can be found  here: https://github.com/UCSC-nanopore-cgl/margin/tree/master/params/phase .

You can modify the one that you want to experiment with, save it as a custom JSON file and provide it to the pipeline with the said parameters.
