### ISSUE TITLE
version of margin in latest docker image

### ISSUE THREAD

**Issue by splaisan** [kishwarshafin/pepper#151]
dear,
I see that the current image r0.8 includes margin 2.2.dev-69f6fff  while the latest margin seem to be at 2.3.1.
Is there a risk that past bugs in margin 2.x affect us?

thanks

**Comment by kishwarshafin** [comment]
@splaisan ,

`2.2.dev-69f6fff` is e2e tested and should not have any bugs. The current margin releases are work that came after the r0.8 release and for incremental future work.
