### ISSUE TITLE
Further output description

### ISSUE THREAD

**Issue by nsanchezcollantes** [kishwarshafin/pepper#152]
Hello,

I wanted to know which of all the output and intermediate files generated gives me the SNPs used by Margin to phase the BAM file. 

Thank you in advance,

Natalia.

**Comment by kishwarshafin** [comment]
@nsanchezcollantes ,

Here's the description of methods that you can find useful: https://github.com/kishwarshafin/pepper/blob/r0.8/docs/misc/pepper_methods.md

The description of each intermediate file is under the text: "All variants are used for haplotagging with margin."

**Comment by nsanchezcollantes** [comment]
Thank you, that was helpful!

I'll close the issue.
