### ISSUE TITLE
No valid VCF entries found!

### ISSUE THREAD

**Issue by infotmatician** [kishwarshafin/pepper#157]
Hi,
Hope you are doing well. I am trying to use the separate bam file per chromosome but getting an error: No Valid VCF Found,  (but pepper predicts all variants in the chromosomes). If I am not splitting the bam file it's working well and I can see variants of each chromosome from vcf file generated by Pepper-Margin-Deepvariant.
What could be the reason?

**Comment by kishwarshafin** [comment]
@infotmatician ,

Can you please give a little more context? Like the error message and the command?

**Comment by infotmatician** [comment]
During the alignment step, I aligned my reads to the whole reference genome and used to default command of Pepper-Margin-Deepvariant for both bam types(split Chr of bam files and without split).
Also the latest version of the Pepper-Margin-Deepvariant, uses the old version of the Margin. When I selected ont_r10_q20 Margin still uses -r94g507 
 The error is:
  >INFO: FINISHED PROCESSING, TOTAL CANDIDATES FOUND: 15
  >INFO: FINISHED PROCESSING, TOTAL VARIANTS IN PEPPER: 13
  >INFO: FINISHED PROCESSING, TOTAL VARIANTS SELECTED FOR RE-GENOTYPING: 2
  >INFO: FINISHED PROCESSING, TOTAL SNP VARIANTS SELECTED FOR RE-GENOTYPING: 2
  >INFO: FINISHED PROCESSING, TOTAL INDEL VARIANTS SELECTED FOR RE-GENOTYPING: 0
  >INFO: TOTAL TIME SPENT ON CANDIDATE FINDING: 0 Min 0 Sec
  >INFO: TOTAL ELAPSED TIME FOR FINDING CANDIDATES: 0 Min 47 Sec
  >CONTIGS FOUND IN PEPPER VCF:
  >7
  > Parsing model parameters from file: /opt/margin_dir/params/phase/allParams.haplotag.ont-r94g507.snp.json
  > Parsed 15 total VCF entries from pepper_output//intermediate_files/PEPPER_VARIANT_FULL.vcf.gz; kept 0 HETs, skipped 0 for region, 0 for not being PASS, 15 for being homozygous, 0 for being INDEL
  No valid VCF entries found!

**Comment by kishwarshafin** [comment]
@infotmatician ,

Are you running this in a small region? It looks like you zoomed into a highly homozygous region of the genome and PEPPER is failing to find any HET variants.

**Comment by infotmatician** [comment]
I am not running against the small location of the chromosome. I run my fastq files against the whole chromosome then I split the bam file per each chromosome after that I am running the P.E.P.P.E.R. 
I am testing my pipeline and I want to add a checkpoint step 
Does the bam file should have homozygous or  HET variants for Pepper to work? 
Does P.E.P.P.E.R. has limitations for completing variant calling such as read length of the fastq file or bam files?
