### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by BrendaLee1** [kishwarshafin/pepper#159]
Hi!
I tried the following commands：
singularity exec --bind /usr/lib/locale/ \
pepper_deepvariant_r0.8.sif \
run_pepper_margin_deepvariant call_variant \
-b "${INPUT_DIR}/${BAM}" \
-f "${INPUT_DIR}/${REF}" \
-o "${OUTPUT_DIR}" \
-p "${OUTPUT_PREFIX}" \
-t "${THREADS}" \
--ont_r9_guppy5_sup
There were no output and the error information like below:
    from pysam.libchtslib import *
ImportError: /soft/anaconda3/lib/python3.8/site-packages/pysam/../../../././libssl.so.1.1: undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0
CentOS Linux release 7.6.1810 (Core)

I tried to install openssl independently, but seems not work. Would you please give me some suggestion about this problem?

Thanks!

Best,
BL

**Comment by kishwarshafin** [comment]
hi @BrendaLee1 ,

Can you please try to install pysam independently to see if you can install pysam?
```
python3 -m pip install pysam
```
If this doesn't work due to permission, please try:
```
python3 -m pip install pysam --user
```
And please put the full log here so I can help you debug this issue.
