### ISSUE TITLE
RefCall vs. PASS

### ISSUE THREAD

**Issue by yifeng-evo** [kishwarshafin/pepper#160]
Hi,

I am not sure why some positions are considered as "refcall", which indicates the "call is homozygous". When I checked the position in IGV, it seems that it is a heterozygous position.  I was wondering how refcall is different from PASS. For example：
`NODE_10237_length_5294_cov_2.741049     216     .       A       AT      17      PASS    .       GT:GQ:DP:AD:VAF:C       0/1:17:36:12:0.333:P
NODE_10237_length_5294_cov_2.741049     239     .       T       A       0       refCall .       GT:GQ:DP:AD:VAF:C       0/0:21:36:11:0.305556:DV`
I am new to VCF files so maybe I didn't understand the format correctly. Could you please help me to clarify this? Thank you!

**Comment by kishwarshafin** [comment]
@yifeng-evo ,

* The variant in position `216` is a PASS variant with `GT` of `0/1` which means it's a het variant.
* The variant in position `239` is a refCall meaning it's likely an error in sequencing platform and assigned GT is `0/0` meaning it's homozygous to the reference.

**Comment by yifeng-evo** [comment]
<img width="975" alt="Screen Shot 2022-08-03 at 2 33 10 PM" src="https://user-images.githubusercontent.com/48135680/182683611-6c7ce604-30db-4d8a-aba4-ff3a743c08c5.png">
It seems to be not a homozygous position in IGV (A in green and T in red). I checked a couple of other refcall positions and they also look similarly. Is it because some reads were filtered due to bad quality? or maybe I used "--pepper_min_coverage_threshold 20" so one allele could be considered as homozygous if alt is supported by <20 reads?

**Comment by kishwarshafin** [comment]
@yifeng-evo ,

There are a variety of things that go into the determination of a site being a true variant or not. Including base_quality, mapping_quality, strand_distribution etc. What it means here is the DeepVariant looked at this site and decided it is not a variant. 

The `--pepper_min_coverage_threshold 20` parameter only affects candidate finding. As you are seeing the variant in the VCF, it means that didn't affect your calling.
