### ISSUE TITLE
Setting Guppy version

### ISSUE THREAD

**Issue by vladimirsouza** [kishwarshafin/pepper#163]
Hi,
I want to use `Pepper-Margin-DeepVariant` with `Singularity` to call variants from nanopore sequencing data. The basecalling was done using Guppy 4.2.2, r9.4.1, hac. But when I use `--help` to see the options, I get only `--ont_r9_guppy5_sup`, `--ont_r10_q20`, or `--hifi`. Is there something like `--ont_r9_guppy4_hac`? If so, how can I download and use it?

In the absence of what I want, I tried `--ont_r9_guppy5_sup`. But I got the error `cp: cannot stat '/opt/pepper_models/PEPPER_VARIANT_ONT_R941_GUPPY5_SUP_V8.pkl': No such file or directory`. Do I have to download this file and save it in my `/opt/pepper_models/`, or is this something that is missing in the container image?
Thanks for reading my message. I'm eager to see your answer. Bests.

**Comment by kishwarshafin** [comment]
hi @vladimirsouza ,

`--ont_r9_guppy5_sup` should work with `hac` reads. Can you please check if you are using the correct version which is `r0.8`

**Comment by vladimirsouza** [comment]
Thank you for your answer. Good to know that it works for `hac`. Does it work with Guppy 4 as well?
Yes, I'm using `r0.8`. How can I solve the `cp: cannot stat '/opt/pepper_models/PEPPER_VARIANT_ONT_R941_GUPPY5_SUP_V8.pkl': No such file or directory` problem?

**Comment by kishwarshafin** [comment]
@vladimirsouza ,

If you are using guppy 4 then the suggestion would be to an older version of the software: https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_docker/ONT_variant_calling.md

To resolve that issue, can you please put down the full command here so I can see if I can locally re-create the issue? There's also a case-study that you can follow here: https://github.com/kishwarshafin/pepper/blob/r0.8/docs/pipeline_singularity/ONT_variant_calling_singularity.md

**Comment by vladimirsouza** [comment]
Here is the code that I used:
```
REF=/home/vbarbo/project_2021/paper_analysis/reference/genome/GRCh38.p13_all_chr.fasta
BAM_DIR=/home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/data_manipulation
OUTPUT_DIR=/home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant
THREADS=20

mkdir -p ${OUTPUT_DIR}/pmdv
singularity exec --bind $OUTPUT_DIR/pmdv/,/usr/lib/locale/ \
  /home/mark/scratch/pepper_deepvariant-r0.8.simg \
  run_pepper_margin_deepvariant call_variant \
  -b ${BAM_DIR}/aln_s.bam \
  -f ${REF} \
  -o ${OUTPUT_DIR}/pmdv \
  -p pepperMarginDeepvariant_calls \
  -t ${THREADS} \
  --ont_r9_guppy5_sup
```

And here are all output message that I get:
```
[08-24-2022 06:49:44] INFO: VARIANT CALLING MODULE SELECTED
[08-24-2022 06:49:44] INFO: [1/9] RUNNING THE FOLLOWING COMMAND
-------
mkdir -p /home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant/pmdv;
mkdir -p /home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant/pmdv/logs;
mkdir -p /home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant/pmdv/intermediate_files;
cp /opt/pepper_models/PEPPER_VARIANT_ONT_R941_GUPPY5_SUP_V8.pkl /home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant/pmdv/intermediate_files
-------
cp: cannot stat '/opt/pepper_models/PEPPER_VARIANT_ONT_R941_GUPPY5_SUP_V8.pkl': No such file or directory
[08-24-2022 06:49:44] ERROR: None]
[08-24-2022 06:49:44] THE FOLLOWING COMMAND FAILED: mkdir -p /home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant/pmdv;
mkdir -p /home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant/pmdv/logs;
mkdir -p /home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant/pmdv/intermediate_files;
cp /opt/pepper_models/PEPPER_VARIANT_ONT_R941_GUPPY5_SUP_V8.pkl /home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant/pmdv/intermediate_files]
```
P.S.: I have permition to write in directory `/home/vbarbo/project_2021/paper_analysis/rebuttal/nanopore/files/ENCFF263YFG/variant_calling_from_nanopore/pepperMarginDeepvariant/pmdv`.

**Comment by vladimirsouza** [comment]
[kishwarshafin](https://github.com/kishwarshafin), Thank you very much.
As suggested here, I switched to the older version [pepper_deepvariant:r0.4](https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_docker/ONT_variant_calling.md), and it looks like the analysis is going all right with my Guppy4-generated sequences now.
Bests.
