### ISSUE TITLE
optimal GPU type

### ISSUE THREAD

**Issue by COMInterop** [kishwarshafin/pepper#164]
Hello,

I try to run PEPPER-Margin-DeepVariant on Amazon EC2 instance with the NVIDIA A10G Tensor Core GPU. It works but only uses a part of the GPU, about 12%:

![Captura de Pantalla 2022-08-26 a la(s) 18 34 46](https://user-images.githubusercontent.com/7071578/187003014-9544f6de-aace-4f82-9b2e-8a708330535e.png)

Is this expected? There is also one with the NVIDIA T4 Tensor Core GPU, or the NVIDIA Tesla M60 GPU. Can you say which is the best?

Also, is there a benefit to have TensorFlow, PyTorch, or MXNet? Or is CUDA sufficient? 

Thank you!

**Comment by kishwarshafin** [comment]
@paracontias 

This is a very difficult question to answer. You can increase the batch size etc. to see how to increase GPU usage. You can find them here: https://github.com/kishwarshafin/pepper/blob/r0.8/docs/usage/usage_and_parameters.md
