### ISSUE TITLE
.csi indexing when phasing

### ISSUE THREAD

**Issue by aguygarner** [kishwarshafin/pepper#169]
My genome chromosomes are too long for .bai indexing. Wondering if there is a parameter to use to index the resulting bam with .csi. At the moment I cannot find this in the markdown.  Thank you.

**Comment by kishwarshafin** [comment]
@aguygarner ,

We have tested this and it should work fine. Please run the pipeline as suggested and you'll see it working.

**Comment by aguygarner** [comment]
I am currently running this under default settings but getting the following error, 

[E::hts_idx_check_range] Region 536879534..536880394 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6
[E::sam_index] Read 'b028d85b-2208-4bb7-a447-efa17d09555d' with ref_name='chrlg1', ref_length=853908666, flags=0, pos=536879535 cannot be indexed
samtools index: failed to create index for "Samplix.831_16.R2R3Myb/Samplix.831_16.R2R3Myb_PEPPER_chrlg6_out/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam": Numerical result out of range
[09-26-2022 14:48:39] ERROR: None]
Traceback (most recent call last):

**Comment by aguygarner** [comment]
it looks like variant calling works fine through pepper but is snagging in margin haplotag?

**Comment by kishwarshafin** [comment]
@aguygarner , sorry for forgetting to reply to this issue. The solution is to do `--dry_run` and run each command independently. Please reopen if this is still an issue for you.
