### ISSUE TITLE
Where can I install dv_models 

### ISSUE THREAD

**Issue by YanJiunLiu** [kishwarshafin/pepper#17]
I am trying to run all the process step by step, but I can't install the  R941_guppy360_snp/model.ckpt-23700 and  ont-3bams-withHP/model.ckpt-33000 . Where can I get these two model.ckpt?

**Comment by kishwarshafin** [comment]
Hi @YanJiunLiu ,

The codebases of PEPPER and DeepVariant have diverged a lot from the initial release. I don't think it's possible at this moment to generate results that are similar to PEPPER-DeepVariant versions that are in the docker. Is there any specific reason to do this? We will make an official release soon with full support. I'd suggest waiting for that version.

**Comment by YanJiunLiu** [comment]
I have solve this problem thanks
