### ISSUE TITLE
pysam not working

### ISSUE THREAD

**Issue by Az513** [kishwarshafin/pepper#170]
Hello,
The installation went well. But when I ran a test it says:
from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

I am using a Centos and do not have pysam on python3.9. I have it on 2.7

Thank you
A

**Comment by kishwarshafin** [comment]
@Az513 python 3 is required for this package. I am unsure about the local installation on centOS, but, can you please provide a little more details on this?
