### ISSUE TITLE
issue in running Pepper

### ISSUE THREAD

**Issue by tahashmi** [kishwarshafin/pepper#173]
Hi @kishwarshafin Can you look into log file [1_pepper.log](https://github.com/kishwarshafin/pepper/files/9832627/1_pepper.log), why the run is not being completed for use case: 
https://github.com/kishwarshafin/pepper/blob/r0.8/docs/pipeline_singularity/HiFi_variant_calling_singularity.md

**Comment by kishwarshafin** [comment]
@tahashmi,

It looks like the run has finished. Do you see something kept running?
