### ISSUE TITLE
./. GQ=0 in gvcf where I have high coverage as homozygous reference

### ISSUE THREAD

**Issue by aguygarner** [kishwarshafin/pepper#175]
Hello. 
I am working with some long read enrichment data. We called gvcfs on this because we wanted to know where our samples were reference versus missing versus real variants. However, we are finding a very high amount of ./. GQ=0 calls where the individuals have high coverage (>150 reads) and look reference. Any thoughts on why this might be and how we can correct for it?

Attached is a photo of a gvcf (top) and the related bam (bottom). In the gvcf variant section there are white sites that are called as ./. but they are clearly homozygous reference in our reads

<img width="1440" alt="Screen Shot 2022-11-01 at 8 23 53 PM" src="https://user-images.githubusercontent.com/74216252/199366208-5fd07517-a37b-47da-bae9-ab89fb4a81a7.png">

As well as what this looks like for a single individual in the g.vcf.

<img width="1025" alt="Screen Shot 2022-11-01 at 10 32 07 PM" src="https://user-images.githubusercontent.com/74216252/199381747-7d60f3c6-996c-4b3e-998a-a5f0186d51fb.png">

**Comment by kishwarshafin** [comment]
Hi @aguygarner ,

Hmm, it does look like it's missing some variants. One thing that comes to mind is that the coverage is a bit too high in this region, and with this coverage, Margin sometimes has difficulty in determining which reads to use for phasing, and overall the phasing quality drops. Can you quickly check if you downsample this to something around 60x-70x if the problem still persists?
