### ISSUE TITLE
Seq2Seq_atn.py

### ISSUE THREAD

**Issue by ElaheA90** [kishwarshafin/pepper#176]
I fount that you have a code for attention based Seq2Seq model Seq2Seq_atn.py for pepper but it seems that you did not use it. Is there any specific reason that you are not using attention based one?

**Comment by kishwarshafin** [comment]
Hello,

Those were exploratory scripts that we either didn't follow through or didn't work. I don't exactly remember what was the case. One thing I remember was that the RNN solution had the highest sensitivity and we were aiming for that in PEPPER.
