### ISSUE TITLE
Local PEPPER installation for variant calling

### ISSUE THREAD

**Issue by leonorpalmeira** [kishwarshafin/pepper#179]
Dear Pepper team,

I am trying to install `PEPPER` locally and have used the following:

```bash
apt-get install -y cmake \
    	    	       make \
		       git \
		       gcc \
		       g++ \
		       autoconf \
		       bzip2 \
		       lzma-dev \
		       zlib1g-dev \
		       libcurl4-openssl-dev \
		       libpthread-stubs0-dev \
		       libbz2-dev \
		       liblzma-dev \
		       libhdf5-dev \
		       python3-pip \
		       python3-virtualenv \
		       virtualenv
git clone https://github.com/kishwarshafin/pepper.git
cd pepper
make
make build
make install
```

I do see `pepper` and `pepper_variant`:

```bash
$ cd venv/bin/
$ ./pepper --version
PEPPER VERSION:  0.8.0
$ ./pepper_variant --version
PEPPER VERSION:  0.8.0
```

But I cannot find the binary `run_pepper_margin_deepvariant` described in your README to run variant calling. Is there anything special that I need to do to install it?

**Comment by kishwarshafin** [comment]
Hello, the `run_pepper_margin_deepvariant` is a part of the docker, it is not part of PEPPER. The docker contains a wrapper that runs PEPPER-Margin-DeepVariant simultaneously. For local development you only installed PEPPER.

**Comment by leonorpalmeira** [comment]
Hello, thanks for your answer! Would it be possible to obtain the Dockerfile describing how the docker is built as well as the code of the `run_pepper_margin_deepvariant` wrapper?

**Comment by kishwarshafin** [comment]
hi @leonorpalmeira , I have added you to the appropriate repo. I'll close this issue.

**Comment by leonorpalmeira** [comment]
Thank you very much!
