### ISSUE TITLE
Calloc issue with docker even after allocating memory - margin polish

### ISSUE THREAD

**Issue by sofiabanu** [kishwarshafin/pepper#180]
Dear Pepper Team,

I've tried running margin polish using docker using the command-
 docker run -it --memory="100g" --memory-swap="200g" -v /media:/media --ipc=host kishwars/pepper_deepvariant:r0.8 margin polish /media/sofia/Files_for_margin/reads_2_assembly_minimap_sorted.bam /media/sofia/Files_for_margin/Assembly.fasta /media/sofia/Files_for_margin/allParams.np.human.r94-g507.json -t 90

I've tried it with a bunch of memory options but the same error occurs.

Running OpenMP with 90 threads.
> Parsing model parameters from file: /media/sofia/Files_for_margin/allParams.np.human.r94-g507.json
Calloc failed with request for -2 lots of 16 bytes

Please help in resolving this issue.

**Comment by kishwarshafin** [comment]
hi @sofiabanu , this issue can be best resolved in the margin repo. It looks like the file placement is incorrect, all files look for base files, if you copied one param then it might be out of sync with the base params file.
