### ISSUE TITLE
"image" doesn't exist error

### ISSUE THREAD

**Issue by rahulmohan** [kishwarshafin/pepper#19]
Hi,

I'm trying to run pepper polish on my own reads and draft, and I get the following error:

`KeyError: "Unable to open object (object 'image' doesn't exist)"
`
It's referring to the following line: `image = hdf5_file['summaries'][image_name]['image'][()]`
in "dataloader_predict.py".

Appreciate any suggestions.

**Comment by kishwarshafin** [comment]
Hi @rahulmohan ,

Can you please put down the command that you are running? Seems like the images it generated got corrupted somehow. I'd suggest cleaning the directory and running it again?

However, I'd need a little more details to debug this properly.

**Comment by rahulmohan** [comment]
Hi @kishwarshafin,

Here is my command:

`pepper polish --bam m54328_180926_222309_9568797/subreads2draft.sorted.bam --fasta m54328_180926_222309_9568797/draft.fa --model_path pepper_r941_guppy344_human.pkl --output_file m54328_180926_222309_9568797_consensus --threads 1 --batch_size 1 --gpu`

I'm trying to run the polishing on a single molecule right now. I loaded in the images that were generated manually to debug and it looks like the "image" member exists but it exists as such: images["summaries"]["m54328_180926_222309"]["9568797"]["ccs_0_1100_0"]["image"], as opposed to "hdf5_file['summaries'][image_name]['image'][()]". 

Maybe I need to rename the reads to avoid it splitting it up like this?

**Comment by kishwarshafin** [comment]
Thank you for going through the debugging part and pointing to the problem exactly. This is a bug then, give me some time to see what exactly is going on. Are you trying to polish the ONT assembly with CCS data?

**Comment by rahulmohan** [comment]
I'm working with PacBio data, I just wanted to try PEPPER out using the human trained model and am interested in re-training the model on my dataset.

**Comment by kishwarshafin** [comment]
@rahulmohan , 

I'm afraid you will not get any improvement if you are using ONT trained model on PacBio data, in fact, I think you will lose accuracy. The error modes are totally different. I do have a plan to extend PEPPER to HiFi data but that is still in development. 

I would strongly suggest not to use the current models on PacBio.

**Comment by kishwarshafin** [comment]
hi @rahulmohan ,

I was unable to replicate this issue internally, can you please share a segment of your bam and fasta file so I can see where exactly this is breaking?

**Comment by kishwarshafin** [comment]
Hi @rahulmohan , going to close this issue as I was not able to re-generate it internally.
