### ISSUE TITLE
PEPPER_variant_calling pipeline in shell scripts instead of docker?

### ISSUE THREAD

**Issue by yingchen69** [kishwarshafin/pepper#20]
Hi,

Is it possible to put PEPPER_variant_calling pipeline in shell scripts instead of docker? We run processes on our clusters and do not have the privileges to run docker. I pulled singularity image from your docker images, but still run into trouble whe trying to run singularity.

Thanks a lot for the help!

Ying

**Comment by kishwarshafin** [comment]
Hi @yingchen69 ,

It is not possible with the limited release version, we will do a full release soon. Hopefully, that'll be compatible.
