### ISSUE TITLE
consider zooming in on the y-axis for the "ideel plots"

### ISSUE THREAD

**Issue by Kirk3gaard** [kishwarshafin/pepper#22]
Hi @kishwarshafin 

I managed to get pepper installed and ran it on a Bacillus pure culture (Like described here https://github.com/kishwarshafin/pepper/blob/r0.1/docs/PEPPER_microbial_data_polishing.md) . I have benchmarked the relative gene lengths against other polishing methods including adding illumina data.

![image](https://user-images.githubusercontent.com/4373417/99968850-f8105c00-2d99-11eb-8ca0-5a24a8aaccda.png)

It appears that Pepper might need a model for bonito v. 0.3.1 to achieve the performance shown in your analysis. Or maybe you can check whether zooming in on the ideel plots in your analysis reveals that some genes are still not full length.

Data not mentioning bonito was basecalled using the latest version of guppy.

**Comment by kishwarshafin** [comment]
@Kirk3gaard ,

Thank you. I think I need to retrain the PEPPER model for Bonito v3.1. The human samples look different too. Thank you for reporting this.

**Comment by kishwarshafin** [comment]
I have added this issue at the top of the readme. Thank you again for reporting.

**Comment by kishwarshafin** [comment]
Hi @Kirk3gaard ,

We have removed small genome polishing functionality from PEPPER. It is currently meant for polishing diploid genomes only. If we go back to polishing haploid assemblies, I will reopen this issue.
