### ISSUE TITLE
Error in Variant Calling Pipeline

### ISSUE THREAD

**Issue by caspargross** [kishwarshafin/pepper#23]
Hi,

I get an error running the Variant Calling from docker. Here is a part of the error log, maybe its just a small typo in the script?
![image](https://user-images.githubusercontent.com/10211013/100139738-312af800-2e90-11eb-9a2d-2b6e68668c27.png)

Best, Caspar

**Comment by kishwarshafin** [comment]
@caspargross , 

The error is in the DeepVariant run:
```bash
returned non-zero exit status 252.
```
There are two possibilities here:
* You don't have sufficient permission to run the docker you are running. Please try adding `--user root` to see if this goes away. I'd suggest trying this on a smaller bam first before you scale to the whole genome. 
* You are on a machine that does not support AVX instruction, in that case, there's nothing much to be done. 

Please see this issue for details: https://github.com/google/deepvariant/issues/345

**Comment by caspargross** [comment]
Hey, kishwar.

I used a testdataset on our (really) old machine which does not support AVX.
Running on another machine works.

Thank you for the answer,
Caspar
