### ISSUE TITLE
Install from source wrong

### ISSUE THREAD

**Issue by masen1991** [kishwarshafin/pepper#24]
hello
i try to iInstall from source,and it get this bug:
[ 78%] Linking CXX shared module PEPPER_SNP.cpython-37m-x86_64-linux-gnu.so
/usr/bin/ld: BFD version 2.20.51.0.2-5.34.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
gmake[3]: *** [PEPPER_SNP.cpython-37m-x86_64-linux-gnu.so] Error 1
gmake[3]: *** Deleting file `PEPPER_SNP.cpython-37m-x86_64-linux-gnu.so'
gmake[3]: Leaving directory `/picb/humpopg-bigdata5/masen/bio/pepper/build/temp.linux-x86_64-3.7'
gmake[2]: *** [CMakeFiles/PEPPER_SNP.dir/all] Error 2
gmake[2]: *** Waiting for unfinished jobs....
[ 85%] Linking CXX shared module PEPPER_HP.cpython-37m-x86_64-linux-gnu.so
/usr/bin/ld: BFD version 2.20.51.0.2-5.34.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
My platform info:
Linux  2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 16 06:12:23 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

Thank you very much!

**Comment by kishwarshafin** [comment]
Hi @masen0407 ,

can you provide a few details about your system? Like OS etc.

**Comment by masen1991** [comment]
hello,
Linux version 2.6.32-431.23.3.el6.x86_64 (mockbuild@x86-027.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Wed Jul 16 06:12:23 EDT 2014
is this right

**Comment by kishwarshafin** [comment]
Hi @masen0407 ,

Do you have permission to run docker on your machine?

**Comment by masen1991** [comment]
Hi,@kishwarshafin
Sorry ,i do not have the permission.And as i work on cluster service,so i hardly can try to tell the Administrator to update some tools because there are other users and any update to key tools may cause them some troublesome.is there any chance you  may consider have a conda version?
Because as i know ,many people work on bioinformation use cluster service and do not have permission to do sudo update or maybe  not have a docker in service,but conda can do.

**Comment by kishwarshafin** [comment]
Hi @masen0407 ,

It seems like your OS version is very old. I don't think just porting things to Conda will help. However, in the future, if we decide to make `PEPPER` available via conda, DeepVariant will still be an issue for your server. Would it be possible to see if you can use singularity?

**Comment by masen1991** [comment]
hello @kishwarshafin 
i try a new service ,INFO like this:
Linux version 3.10.0-1127.19.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Aug 25 17:23:54 UTC 2020
and i follow this:
git clone https://github.com/kishwarshafin/pepper.git
cd pepper
make install
. ./vnev/bin/activate

pepper --help
pepper polish --help

########

(pepper) (base) -bash-4.2$ path_to/pepper/venv/bin/pepper -h
Traceback (most recent call last):
  File "./pepper", line 33, in <module>
    sys.exit(load_entry_point('pepper-polish==0.1.5', 'console_scripts', 'pepper')())
  File "/picb/humpopg-bigdata5/masen/bio/pepper/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/picb/humpopg-bigdata5/masen/bio/pepper/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/picb/humpopg-bigdata5/masen/bio/pepper/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/picb/humpopg-bigdata5/masen/bio/pepper/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/picb/humpopg-bigdata5/masen/bio/pepper/venv/lib/python3.7/site-packages/pepper_polish-0.1.5-py3.7-linux-x86_64.egg/pepper/pepper.py", line 5, in <module>
    from pepper.modules.python.polish import polish
  File "/picb/humpopg-bigdata5/masen/bio/pepper/venv/lib/python3.7/site-packages/pepper_polish-0.1.5-py3.7-linux-x86_64.egg/pepper/modules/python/polish.py", line 1, in <module>
    from pepper.build import PEPPER
ImportError: /picb/humpopg-bigdata5/masen/bio/pepper/venv/lib/python3.7/site-packages/pepper_polish-0.1.5-py3.7-linux-x86_64.egg/pepper/build/PEPPER.cpython-37m-x86_64-linux-gnu.so: undefined symbol: libdeflate_free_compressor

make install go well and i see no bug ,do you know what happen?
And also i am trying to use singularity on DeepVariant first,still i meet many bug~~,so just trying

**Comment by masen1991** [comment]
hello @kishwarshafin
i try  to use singularity to run DeepVariant and it work. so can u add some workflow about how to use singularity to use 
pepper? 
thank you very much

**Comment by kishwarshafin** [comment]
hi @masen0407 , thank you for reporting this. I'll make sure that the next release is supported by singularity.
