### ISSUE TITLE
Bat genome optimal parameters

### ISSUE THREAD

**Issue by desmodus1984** [kishwarshafin/pepper#26]
Hi,
I am doing demographic inference in bats and I would like to have a contiguous genome to use long-range haplotypic data. 
I have found that many programs have "hidden parameters" that can optimize an assembly. So, before jumping and trying, and perhaps wasting time, I would like to ask for your hints and get perhaps some recommendation settings. I will be extremely grateful.

I have short-read data, 100 bps reads, ~65X; and long-read data, ~20X - average size 2K, up to 250kbps. As I mentioned my final goals is to have a good quality contiguous genome assembly for variant calling, demographic inference, and potentially being capable to call not only SNPs but also -hopefully-  haplotypic data, and even large structural variants.

Which workflow do you recommend?
Also, I was reading that there is the need for a model and I couldn't find any information about that. 

Looking forward for your response

Juan Pablo

**Comment by kishwarshafin** [comment]
Hi @desmodus1984 ,

This sounds like a fascinating study. Would it be possible to send me an email at shafin@ucsc.edu so we can discuss this in detail? Can you please include the sequencing technology, sequencing machine, and a little more details about that data you have? This is more of an experimental setup issue than a tool issue.
