### ISSUE TITLE
About chicken genome and guppy 4.2.2

### ISSUE THREAD

**Issue by Johnsonzcode** [kishwarshafin/pepper#27]
Hi, 
I am doing chicken genome assembly, my long-reads is about 80X from guppy 4.2.2 basecalling and 13X from GridON guppy 4.0.2. I used them all to do assembly.
As your `README.md`, after downloading models I don't know which one is suitable for me.
``` bash
pepper_r941_bonito_microbial.pkl
pepper_r941_guppy305_microbial.pkl
pepper_r941_guppy305_human.pkl
pepper_r941_guppy344_human.pkl
```
If no one is suitable for me, should I train models for myself ?

Looking forward for your response.
Johnsonz

**Comment by kishwarshafin** [comment]
@Johnsonzcode , I have a few questions, can you please let me know which assembler you used? Also, the N50 of the assembly and did you map the reads back to the assembly, if yes what is the average coverage?

**Comment by Johnsonzcode** [comment]
Assembler is NextDenovo, I did map reads back to the assembly, N50 of assembly is 53M. I don't know average coverage of the `bam` file, how to check it ?

**Comment by kishwarshafin** [comment]
@Johnsonzcode , you can use mosdepth (https://github.com/brentp/mosdepth) for the average coverage. I think the best model for you to use would be `pepper_r941_guppy305_human.pkl` as it performs best on high-coverage samples.

**Comment by Johnsonzcode** [comment]
Thank you for your suggestion, I will check my depth, and I am wondering the run time of pepper?

**Comment by kishwarshafin** [comment]
Given the size of the genome and coverage, if you run on a CPU-only machine it'd take about 12-16hours. It also depends on the number of contigs and some other factors. But my assumption would be 16h+ on a 3.0GHz 64core machine.
