### ISSUE TITLE
error when parallel deepvariant make_examples

### ISSUE THREAD

**Issue by yingchen69** [kishwarshafin/pepper#30]
Hi,

I ran PEPPER-DeepVariant pipeline test sample successfully, but got error when I ran my real data. I ran the pipeline for 12 samples and only 2 ran successfully. The other 10 runs all got error at the "time seq 0 23 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples ..." step.

Here is my sample command to run cpu version on cluster using singularity:

module purge
module load singularity/3.5.3
BASE="/project1/yc790-001/work/T2T_DRA008154/DRR171454chm13"
INPUT_DIR="${BASE}/input/data"
REF="chm13.draft_v1.0.fasta"
BAM="DRR171454chm13.sorted.bam"
THREADS="24"
OUTPUT_DIR="${BASE}/output"
OUTPUT_VCF="PEPPER_HP_DEEPVARIANT_FINAL_OUTPUT.vcf.gz"
PEPPER_SNP_MODEL=PEPPER_SNP_R941_guppy360_model.pkl
PEPPER_HP_MODEL=PEPPER_HP_R941_guppy360_model.pkl
srun singularity run -B /usr/lib/locale/:/usr/lib/locale/ /project1/yc790-001/work/singularityFiles/pepper_deepvariant_cpu_latest_caliburn_singularity_3_5_3.sif /opt/run_pepper
_deepvariant.sh -b "${INPUT_DIR}/${BAM}" -f "${INPUT_DIR}/${REF}" -t ${THREADS} -o "${OUTPUT_DIR}" -x 1 -p "${INPUT_DIR}/${PEPPER_SNP_MODEL}" -q "${INPUT_DIR}/${PEPPER_HP_MODEL
}"

The following is the error message:

parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /project1/yc790-001/work/T2T_DRA008154/DRR171431chm13/input/data/chm13.draft_v1.0.fasta --reads /project1/yc790-001/work/T2T_DRA008154/DRR171431chm13/output/WHATSHAP.PHASED.bam --examples /project1/yc790-001/work/T2T_DRA008154/DRR171431chm13/output/dv_intermediate_outputs/make_examples.tfrecord@24.gz --alt_aligned_pileup diff_channels --parse_sam_aux_fields --proposed_variants /project1/yc790-001/work/T2T_DRA008154/DRR171431chm13/output/PEPPER_HP_OUPUT.vcf.gz --norealign_reads --sort_by_haplotypes --variant_caller vcf_candidate_importer --task 6

real	11m59.972s
user	11m47.093s
sys	0m12.149s
I1227 13:21:53.028220 47002687478464 run_deepvariant.py:321] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 332, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 319, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 23 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/project1/yc790-001/work/T2T_DRA008154/DRR171431chm13/input/data/chm13.draft_v1.0.fasta" --reads "/project1/yc790-001/work/T2T_DRA008154/DRR171431chm13/output/WHATSHAP.PHASED.bam" --examples "/project1/yc790-001/work/T2T_DRA008154/DRR171431chm13/output/dv_intermediate_outputs/make_examples.tfrecord@24.gz" --alt_aligned_pileup "diff_channels" --parse_sam_aux_fields --proposed_variants "/project1/yc790-001/work/T2T_DRA008154/DRR171431chm13/output/PEPPER_HP_OUPUT.vcf.gz" --norealign_reads --sort_by_haplotypes --variant_caller "vcf_candidate_importer" --task {}' returned non-zero exit status 247.

Since I had two samples finished successfully, I could not tell what went wrong.

Any suggestion?

Thanks a lot!

Ying

**Comment by kishwarshafin** [comment]
@yingchen69 ,

Can you please send me a description of your experimental setup (what are you trying to achieve with your project) via email at shafin@ucsc.edu, as the pipeline you have is not officially supported it's very hard to debug issues like this. I can possibly help you better with a newer version of the pipeline.

**Comment by yingchen69** [comment]
Hi Kishwar,

Thanks a lot for the quick response.

Actually our experiment design is very simple. We downloaded WGS PromethION fastq data of 6 cancel cell lines from DRA008154 data set, and then aligned reads to hg38 and chm13 respectively using winnowmap. At last we want to do variant call using pepper-deepvariant pipeline. The purpose is to see if chm13 genome can improve variant calling in cancer cell lines.

Thanks a lot for the help!

Ying

________________________________

**Comment by kishwarshafin** [comment]
@yingchen69 , I'm closing this issue as it's mostly regarding support to a different reference which we are resolving separately.
