### ISSUE TITLE
Cannot locate fasta file

### ISSUE THREAD

**Issue by tomh1lll** [kishwarshafin/pepper#33]
When attempting to run the polish step, I get the following error:

> INFO: POLISH MODULE SELECTED

> ERROR: CAN NOT LOCATE FASTA FILE

though I provide a fasta file in my submission script:

`singularity exec -B $PWD:$PWD pepper_latest.sif pepper polish \
--bam $PWD/BAM/HFC645.recal.bam --fasta /data/NCBR/references/human/hg38/Homo_sapiens_assembly38.fasta \
--model_path $PWD/pepper_models/pepper_r941_guppy344_human.pkl \
--output_file $PWD/pepper_out/HFC645 --threads 4 --batch_size 128`

The script was run in singularity as an alternative to docker, the --help page loads properly, so I am certain it is not an issue with singularity.

Any help with this would be appreciated.

**Comment by kishwarshafin** [comment]
@tomh1lll , were you able to solve the issue?

**Comment by tomh1lll** [comment]
> 
> 
> @tomh1lll , were you able to solve the issue?

Yes thank you, it was an issue with my directory organisation in the end.
