### ISSUE TITLE
Question regarding the use of base quality scores

### ISSUE THREAD

**Issue by lbal-biomat** [kishwarshafin/pepper#36]
Hi, 

Thanks for another great tool.
This is not really an issue but a question. I'd like to know if pepper-variant uses the base quality scores stored in the bam files.
Best regards,

L.

**Comment by kishwarshafin** [comment]
@lbal-biomat ,

Yes, the variant calling pipeline, PEPPER-DeepVariant, uses base quality to filter candidate variants as well as a feature for the convolutional neural network used in DeepVariant.

**Comment by lbal-biomat** [comment]
Thank you very much for your quick response!
