### ISSUE TITLE
Train model for my specific organism

### ISSUE THREAD

**Issue by Irsan88** [kishwarshafin/pepper#37]
Is it possible to train a model to be used for variant calling with deepvariant with my specific organisms and nanopore instrument? We are working with yeast and bacterial genomes, and I am afraid the pre-trained models provided might not be sufficient

**Comment by kishwarshafin** [comment]
hi @Irsan88 , 

At this moment it is not possible to train PEPPER-DeepVariant in this manner. Our methods are designed to work with GIAB truth sets and will require extensive work to support training non-model organisms.

**Comment by Irsan88** [comment]
OK clear, thanks for your response
