### ISSUE TITLE
Any chance of a deepvariant model for bonito-basecalled data?

### ISSUE THREAD

**Issue by oneillkza** [kishwarshafin/pepper#39]
Hi there!

I've been working through Nanopore's suggested workflow for SNV calling, and realised that, while there is a medaka model now released for bonito-basecalled data, the deepvariant models within the pepper container only go up to guppy 3.6.0. Are there plans in the works for a model appropriate for bonito basecalls?

Thanks!

**Comment by kishwarshafin** [comment]
hello @oneillkza ,

The development paths of `PEPPER-DeepVariant` and `Medaka` are different. I can not say when we can support Bonito.
