### ISSUE TITLE
Alignment command to reproduce results

### ISSUE THREAD

**Issue by lbal-biomat** [kishwarshafin/pepper#43]
Dear Kishwar,

I'm trying out the pepper-deepVariant pipeline for ONT, and first I'd like to reproduce your results from scratch. Would you mind sharing the command you used to align your reads to get the bam file? Is the set of reads you used for the alignment public?

Thanks,
Best regards

**Comment by kishwarshafin** [comment]
@lbal-biomat ,

All of the commands and data sources are provided in the [Supplementary notes](https://www.biorxiv.org/content/10.1101/2021.03.04.433952v1.supplementary-material). 

There's one issue we have with Margin's deterministic behavior https://github.com/kishwarshafin/pepper/issues/42. We are hoping to publish a patch by next week. But you should be able to re-generate the numbers within a very close range without any problem.

**Comment by lbal-biomat** [comment]
Thanks for your answer! Much appreciated. I'll close this.

**Comment by lbal-biomat** [comment]
Hi @kishwarshafin 

I'm reopening because I have some following up questions. The first one is that I noticed that the bam file available to download is called "HG002_ONT_50x_2_GRCh38.chr20.bam". Does that "_2" mean that only "GM24385_2_Guppy_4.2.2_prom.fastq.gz" was used to produce it or were the 3 fastq.gz used?

The other problem is that I'm encountering an error while running the pipeline with my own bam. I'm unsure if the error occurs while generating the images or right after it, but I'm attaching the log. The error message is "ERROR: A process in the process pool was terminated abruptly while the future was running or pending." It occurs consistently at the same point. The errors that follow must be a direct result of that first error.

This is the script to get the bam and to run the pipeline:

```
BASE="${HOME}/pepper-deepvar/HG002/original"

# Set up input data
INPUT_DIR="${BASE}/input"
REF="GRCh38_no_alt.chr20.fa"
READS="GM24385_2_Guppy_4.2.2_prom.fastq.gz  \
  GM24385_2_Guppy_4.2.2_prom.fastq.gz \
  GM24385_3_Guppy_4.2.2_prom.fastq.gz"


# Set the number of CPUs to use
THREADS="30"

# Set up output directory
OUTPUT_DIR="${BASE}/output"
OUTPUT_PREFIX="HG002_ONT_50x_2_GRCh38_PEPPER_Margin_DeepVariant.chr20"

PREFIX="GM24385chr20"

# Set the truth files for evaluation
TRUTH_VCF="HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
TRUTH_BED="HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed"


# Create dirs
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${INPUT_DIR}"


# Make the bam file


minimap2 -ax map-ont -t ${THREADS} ${INPUT_DIR}/${REF} ${INPUT_DIR}/${READS} | \
  samtools view -hb -F 0x904 | \
  samtools sort -@${THREADS} -o ${INPUT_DIR}/${PREFIX}.sorted.bam -
samtools index -@${THREADS} ${INPUT_DIR}/${PREFIX}.sorted.bam


# Run the pipeline

sudo docker run --ipc=host \
-v "${INPUT_DIR}":"${INPUT_DIR}" \
-v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
kishwars/pepper_deepvariant:r0.4 \
run_pepper_margin_deepvariant call_variant \
-b "${INPUT_DIR}/${PREFIX}.sorted.bam" \
-f "${INPUT_DIR}/${REF}" \
-o "${OUTPUT_DIR}" \
-p "${OUTPUT_PREFIX}" \
-t ${THREADS} \
--ont
```

I checked the integrity of the bam file with samtools quickcheck and it seems fine. Do you have an idea of what might be happening? The pipeline runs perfectly with the sample bam file available to download. Any help will be appreciated.

Kind regards

[1_pepper_snp.log](https://github.com/kishwarshafin/pepper/files/6245216/1_pepper_snp.log)

**Comment by kishwarshafin** [comment]
@lbal-biomat the 2 in `HG002_ONT_50x_2_GRCh38.chr20.bam` is short for `to`. It means the reads are aligned to GRCh38.

In your script you are aligning the flowcells of whole genome data to `chr20` only:
```
REF="GRCh38_no_alt.chr20.fa"
READS="GM24385_2_Guppy_4.2.2_prom.fastq.gz  \
GM24385_2_Guppy_4.2.2_prom.fastq.gz \
GM24385_3_Guppy_4.2.2_prom.fastq.gz"
```  
 You need to use the full GRCh38 to align the reads against it. I would do this in two steps. First align the reads to the reference and QC it and then run the variant calling pipeline.

The bam we have provided contains only `chr20`

**Comment by lbal-biomat** [comment]
Thanks @kishwarshafin , it's running without problems now. Closing again.
