### ISSUE TITLE
GPU based Singularity container image

### ISSUE THREAD

**Issue by tahashmi** [kishwarshafin/pepper#44]
Hi @kishwarshafin ,

Can you please create the GPU based Singularity container image for your variant calling pipeline? 

Thanks.

**Comment by kishwarshafin** [comment]
@tahashmi ,

The docker image you are pulling is fully capable of using GPUs. You need to make sure that `singularity` is properly configured for GPUs: https://sylabs.io/guides/3.5/user-guide/gpu.html and then run the same command you are running for PEPPER-Margin-DeepVariant with a `-g` flag that enables the use of GPUs.

You can use this as a reference for your command: https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_docker_gpu/ONT_variant_calling_gpu.md

Let me know if you have any questions.

**Comment by tahashmi** [comment]
Okay. Thanks.
