### ISSUE TITLE
"Critical" errors don't stop the pipeline from continuing

### ISSUE THREAD

**Issue by ASLeonard** [kishwarshafin/pepper#49]
This may be more preference, but I noticed errors which definitely will cause pepper to fail don't stop pepper from continuing, so then trivially hitting more errors at every step until the end.

For this example, I forgot to index my bam file, which is ultimately the root error, but the last error message is an unhelpful "None" error encountered in `margin phase`.

```
time pepper_snp call_variant -b ...
-------
INVALID BAM INDEX FILE. PLEASE CHECK IF FILE IS INDEXED: ...

INFO: [3/8] RUNNING THE FOLLOWING COMMAND
-------
mv pepper_snp/*.vcf PEPPER_SNP_OUPUT.vcf; 
bgzip PEPPER_SNP_OUPUT.vcf; 
...
-------
mv: cannot stat 'pepper_snp/*.vcf': No such file or directory
[bgzip] No such file or directory: PEPPER_SNP_OUPUT.vcf
...
CONTIGS FOUND IN PEPPER SNP VCF:

INFO: [4/8] RUNNING THE FOLLOWING COMMAND
-------
time margin phase ...
mv *.bam MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam; 

-------
Could not read from vcf file: PEPPER_SNP_OUPUT.vcf.gz
mv: cannot stat '*.bam': No such file or directory

ERROR: None]
ERROR ENCOUNTERED IN COMMAND: time margin phase ...
None
```

It isn't that hard to trace it back to the real error, but also just burns time when something like `set -e` pipefail would have terminated the run near the start.

**Comment by kishwarshafin** [comment]
Hi @ASLeonard ,

Thank you for raising the issue. The program that stitches all four modules need to be more robust in producing the error messages, that is right. The development of the independent modules is so rapid at this moment that it's difficult to settle down on when to freeze and optimize the production pipeline. I will keep this in mind and will try to provide something that is more useful and robust in the next release.
