### ISSUE TITLE
Slower than expected runtimes when using older basecallers

### ISSUE THREAD

**Issue by ASLeonard** [kishwarshafin/pepper#54]
Hey Kishwar,
Just opening this as a separate issue from #52, so that doesn't become too off topic.

As a quick summary, using older versions of guppy (pre v3.6.0) seems to result in pepper suggesting a huge number of indels compared to SNPs. This is likely causing later steps to proceed very slowly, particularly the deepvariant make_examples step.

**Comment by ASLeonard** [comment]
I had been running the deepvariant make_examples step on 96 cores for about 24 hours before the jobs were killed. They had generally processed ~150k candidates, which is much less than I've seen in pure deepvariant cases, so I am assuming they are still a far way off from completion. It may just be too much error in the raw reads to be overcome by the trained model.

I do have data on a different animal that is guppy 4, but only about 30x coverage, so I'll see if that works with the expected speed.

**Comment by ASLeonard** [comment]
It looks like there is still a 10x slowdown compared to raw deepvariant make_examples, so perhaps this is more in line with expectations. Hopefully it will complete in a reasonable time.

There is almost a 1:1 ratio of SNP:indel for this dataset, so agrees well with your prediction on the basecaller causing issues.

**Comment by kishwarshafin** [comment]
@ASLeonard , can you please run `bcftools stats` on the set of candidate variants and post it here. And thank you for sharing the details of the runs, it's very helpful. We have purged all of our old data as they were of no use.

**Comment by ASLeonard** [comment]
For PEPPER_HP_OUTPUT_1.vcf.gz
```
SN	0	number of samples:	1
SN	0	number of records:	5152504
SN	0	number of no-ALTs:	0
SN	0	number of SNPs:	2928229
SN	0	number of MNPs:	0
SN	0	number of indels:	2236771
SN	0	number of others:	2
SN	0	number of multiallelic sites:	104557
SN	0	number of multiallelic SNP sites:	13085
```
For PEPPER_HP_OUTPUT_2.vcf.gz
```
SN	0	number of samples:	1
SN	0	number of records:	5593276
SN	0	number of no-ALTs:	0
SN	0	number of SNPs:	3387301
SN	0	number of MNPs:	0
SN	0	number of indels:	2220228
SN	0	number of others:	1
SN	0	number of multiallelic sites:	112467
SN	0	number of multiallelic SNP sites:	20015
```

**Comment by kishwarshafin** [comment]
So you are seeing about a 66% decrease in the total number of candidate variants. In this run, I'm expecting the make_examples to take about ~7h per haplotype, and then call variants would again take about ~6h, so the total you'd get ~13h per haplotype. Please let me know if you see things differently.

Also, I want to emphasize that variant calling and assembly polishing are two very different problems. We put in a lot of effort to make sure these problems are solved correctly. For example, we do not over-polish your genome and introduce an extremely high number of FPs that hurts downstream analysis. The DeepVariant you are using here is a rows model that generates 3x the number of channels so is expected to be slower than the variant calling pipeline. It is possibly not ideal run-time-wise but I am hoping that you will get a well-polished assembly.

**Comment by ASLeonard** [comment]
The pipeline finished in reasonably time with this other set of data. The runtimes were in line with your expectation, make_examples a bit faster, call_variants a slower (maybe 2x, but I've observed this really is affected in deepvariant by which node in our HPC runs the job).

It isn't easy to compare directly as the v0.1 polishing was haploid, compared to diploid in v0.4, but the QVs were pretty similar, both around 35.1.

I'll run this next week with a trio done with guppy 4.0, to see if the times are also as expected.

**Comment by kishwarshafin** [comment]
@ASLeonard , 

Thank you for the update! As you know, our current polishing method can not solve heterozygous structural variants, the overall quality of the diploid assembly gets affected by that. So comparing the QV of a collapsed haploid assembly against the QV of a partial diploid assembly is not apples-to-apples. When you are comparing a diploid assembly, you are penalizing it more by expecting it to resolve heterozygous sites. 

Thank you for using the pipeline and reporting that it worked well in your case. I will close this issue for now. Please feel free to re-open if you have issues with v4.0 data.
