### ISSUE TITLE
No InDels 

### ISSUE THREAD

**Issue by husamia** [kishwarshafin/pepper#55]
I am running the pipeline on ONT bams generated with minimap2. The SNPs are called but there are no InDels. Why is that?

`docker run --ipc=host -v kishwars/pepper_deepvariant:r0.4 run_pepper_margin_deepvariant call_variant -b -f hg19.fa -o pepper_out --ont -r chr22:42520501-42528812 -t 10 -s  --phased_output 
`

Deepvariant should call Indels as I have tested it with this data. Is there some option missing for indels?

There are three VCF in the output 

HP_OUTPUT, SNP_OUTPUT and name.vcf 

it's not in any of those.

![image](https://user-images.githubusercontent.com/13439952/117317332-6b44f080-ae57-11eb-928e-5a58937ca902.png)

**Comment by kishwarshafin** [comment]
@husamia , it is possible that you are running it on such a small region that phasing wasn't able to phase the reads in this region. Can you please run it on the entire `chr22` and see if it's still happening?

**Comment by husamia** [comment]
> @husamia , it is possible that you are running it on such a small region that phasing wasn't able to phase the reads in this region. Can you please run it on the entire `chr22` and see if it's still happening?

I only have reads in this region, it's PCR amplicons. With that, should I still change -r to chr22 and rerun it?

![image](https://user-images.githubusercontent.com/13439952/117319958-ca0b6980-ae59-11eb-90d7-bf147c7985dc.png)

**Comment by kishwarshafin** [comment]
That is very interesting. On your IGV track, can you please left-click the bam track and select "Color alignments by > tag" and then type in "HP" in the pop-up box. And then select left-click again and select "Group alignments by> tag" and type in "HP" and post the output here?

**Comment by husamia** [comment]
> That is very interesting. On your IGV track, can you please left-click the bam track and select "Color alignments by > tag" and then type in "HP" in the pop-up box. And then select left-click again and select "Group alignments by> tag" and type in "HP" and post the output here?

Yes. It works very well for other samples. But for some reason this sample it didn't work.

![image](https://user-images.githubusercontent.com/13439952/117322215-cd9ff000-ae5b-11eb-9133-b2d9ed56b28c.png)

**Comment by husamia** [comment]
For this sample I downsampled at 100X, 500X and 1000X. It give me error for the 100X but not for 500X and 1000X

Running OpenMP with 10 threads.
> Parsing model parameters from file: /opt/margin_dir/params/misc/allParams.ont_haplotag.json
> Parsed 25 HET VCF entries from pepper_out/barcode01.fastq_6K_Q97.fastq.gz.sam.bam_100X.bam/PEPPER_SNP_OUPUT.vcf.gz; skipped 0 for region, 0 for not being PASS, 25 for being homozygous, 0 for being INDEL
> Set up bam chunker in 0s with chunk size 100000 and overlap 10000 (for region=chr22:42520501-42528812), resulting in 0 total chunks
> Found no valid reads!

still didn't detect the InDel


Running OpenMP with 10 threads.
> Parsing model parameters from file: /opt/margin_dir/params/misc/allParams.ont_haplotag.json
> Parsed 25 HET VCF entries from pepper_out/barcode01.fastq_6K_Q97.fastq.gz.sam.bam_1000X.bam/PEPPER_SNP_OUPUT.vcf.gz; skipped 0 for region, 0 for not being PASS, 24 for being homozygous, 0 for being INDEL
> Set up bam chunker in 0s with chunk size 100000 and overlap 10000 (for region=chr22:42520501-42528812), resulting in 1 total chunks
> Ordering chunks by estimated depth
> Setup complete, beginning run
> Starting merge
> Merging results from 1 chunks.
> Merging 100% complete (1/1).  Estimated time remaining: 0s
> Merging took 0s
> Merge cleanup took 0s
  Separated reads with divisions: H1 0, H2 0, and H0 825
> Wrote haplotyped bams in 1s
> Finished phasing in 1s.

**Comment by kishwarshafin** [comment]
@husamia , the reason is PEPPER SNP is picking all of the HOM-ALT variants in this region. As there are no heterozygous variants it is unable to phase this region with confidence. Phasing is absolutely critical for INDELs and heterozygous variants are critical for phasing. However, we have options that you can use to call variants in highly homozygous regions. Let me post something quickly for you to see if you can at least get the candidate variants.

**Comment by husamia** [comment]
> @husamia , the reason is PEPPER SNP is picking all of the HOM-ALT variants in this region. As there are no heterozygous variants it is unable to phase this region with confidence. Phasing is absolutely critical for INDELs and heterozygous variants are critical for phasing. However, we have options that you can use to call variants in highly homozygous regions. Let me post something quickly for you to see if you can at least get the candidate variants.

it's a real indel in this case so it should call it regardless if it can find the phase.

**Comment by kishwarshafin** [comment]
@husamia , the most difficult error mode of ONT is INDELs. So we designed the RNN to reduce the erroneous INDELs from being picked up. In regions where the resolution is small (reads are short) and phasing is bad, the RNN can easily think these deletions are erroneous. The candidate ranking maximizes haplotype-likelihoods as you can read in the manuscript we posted. As you have zoomed in to a highly homozygous region of the genome where reads are very short, you are seeing this behavior.

**Comment by husamia** [comment]
> @husamia , the most difficult error mode of ONT is INDELs. So we designed the RNN to reduce the erroneous INDELs from being picked up. In regions where the resolution is small (reads are short) and phasing is bad, the RNN can easily think these deletions are erroneous. The candidate ranking maximizes haplotype-likelihoods as you can read in the manuscript we posted. As you have zoomed in to a highly homozygous region of the genome where reads are very short, you are seeing this behavior.

I understand now and this is the only sample I had problem with in terms of phasing. I also have same problem with the Deepvariant-Whatshap-Deepvariant as well but in that case the indel was called and the phase was not determined. For my application, can I prioritize calling the indel over phasing?

**Comment by husamia** [comment]
@kishwarshafin Let me know what the option is and I will test it and report back.

**Comment by kishwarshafin** [comment]
Hi @husamia , can you please try this:
```bash
docker run --ipc=host \
-v /data:/data \
kishwars/pepper_deepvariant:test-v0.5-rows \
pepper_variant call_variant \
-b MARGIN.haplotagged.bam \
-f hg19.fa \
-m /opt/pepper_models/PEPPER_HP_R941_ONT_V4.pkl \
-o pepper_out_freq \
-hp \
-s DEFAULT \
-t 10 \
-r chr22:42520501-42528812 \
--freq_based \
--freq 0.10
```
This is an experimental version of PEPPER so you'll have to download a new docker container.

**Comment by husamia** [comment]
It's calling the InDel. But also calling many indels that are not real.

What are the -hp and why no --ont and --phased_output? 

![image](https://user-images.githubusercontent.com/13439952/117354264-2339c400-ae7f-11eb-9228-49a0351a94e0.png)

**Comment by kishwarshafin** [comment]
@husamia , sorry if I wasn't clear. These are candidate variants, you'd still need to run DeepVariant to filter out the false-positive calls. This is how you would run DeepVariant on this vcf:
```bash
# First zip and tabix the PEPPER_HP.vcf
bgzip PEPPER_HP.vcf
tabix -p vcf PEPPER_HP.vcf.gz
```

```bash
time docker run --ipc=host \
-v /data:/data \
kishwars/pepper_deepvariant:test-v0.5-rows \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--customized_model=/opt/dv_models/ont_0317_rows/model.ckpt-170600 \
--ref=hg19.fasta \
--reads=MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam \
--output_vcf=DeepVariant_output.vcf.gz \
--intermediate_results_dir=/deepvariant_intermediate_output/ \
--num_shards=10 \
--make_examples_extra_args="partition_size=10000,max_reads_per_partition=5000,alt_aligned_pileup=rows,realign_reads=false,min_mapping_quality=1,min_base_quality=1,sort_by_haplotypes=true,parse_sam_aux_fields=true,add_hp_channel=false,variant_caller=vcf_candidate_importer,proposed_variants=PEPPER_HP.vcf.gz"
```

Please set the filepaths, specifically `proposed_variants=PEPPER_HP.vcf.gz` correctly. Once done, you will have the variants in `DeepVariant_output.vcf.gz` which should have the false-positive variants removed.

**Comment by husamia** [comment]
> Hi @husamia , can you please try this:
> 
> ```shell
> docker run --ipc=host \
> -v /data:/data \
> kishwars/pepper_deepvariant:test-v0.5-rows \
> pepper_variant call_variant \
> -b MARGIN.haplotagged.bam \
> -f hg19.fa \
> -m /opt/pepper_models/PEPPER_HP_R941_ONT_V4.pkl \
> -o pepper_out_freq \
> -hp \
> -s DEFAULT \
> -t 10 \
> -r chr22:42520501-42528812 \
> --freq_based \
> --freq 0.10
> ```
> 
> This is an experimental version of PEPPER so you'll have to download a new docker container.

If we step back for a second. 

Can you explain a little bit what you changed? I am still not getting phased output for all the other samples which were successful with the experimental version. I am trying to decide when to run the experimental version.

**Comment by kishwarshafin** [comment]
@husamia , 

In this mode, you are running the individual modules of `PEPPER-DeepVariant`. So, instead of doing allele-likelihood-based candidate-finding with `PEPPER-HP`, you did a frequency-based candidate finding, where all candidates with allele frequency of 0.10 or higher are reported. Next, you will do variant calling with DeepVariant to get the variants. And finally, you will phase the variants with Margin. This is to see if you get a good set of variants in this region.

**Comment by kishwarshafin** [comment]
@husamia ,

We have discussed the issues with the amplicon data. What we would suggest is to add enough flanking regions on both sides of your target sequence so you can capture heterozygous variants that enable phasing of your region of interest. Without the heterozygous variants, it will not be possible for the methods we have developed to be successful in these regions. We are planning to release a backup model for targeted amplicon sequence data. But in this case, where everything is extremely homozygous, our methods will not be able to produce sensible variant calls.

I will close this issue for now and will give you an update once we get to the point where we can officially support targeted sequencing.

**Comment by leonorpalmeira** [comment]
Thanks a lot!
