### ISSUE TITLE
Support multiple ranges in -r option

### ISSUE THREAD

**Issue by hjaltithorisleifsson** [kishwarshafin/pepper#56]
Hello

It would be nice to be able to specify multiple ranges in the -r option, both just by giving a comma-separated list of ranges or giving a file (e.g. tsv file with contig in first colum, start in second and end in third).

Best regards,
Hjalti

**Comment by kishwarshafin** [comment]
@hjaltithorisleifsson ,

Are you using our pipeline for amplicon sequenced data? I am trying to understand the use case. As we use long-range variant information (i.e. phasing), running the pipeline on an entire chromosome will always give you better performance than running it on small chunks.

**Comment by kishwarshafin** [comment]
@hjaltithorisleifsson ,

Closing it due to inactivity, please reopen if you have more queries.
