### ISSUE TITLE
Consensus warning about overlapping variants

### ISSUE THREAD

**Issue by ASLeonard** [kishwarshafin/pepper#57]
Hi Kishwar,
When running pepper v0.4 in the ONT polishing mode, I noticed when doing the `bcftools consensus` step with the DV_hap1 vcf output that I was getting dozens or so of warnings per contig about the below
```
The site 0:258412 overlaps with another variant, skipping...
```

Everything finishes smoothly, and the QV does improve to QV35. Is this mostly a harmless warning?

Thanks,
Alex

**Comment by kishwarshafin** [comment]
@ASLeonard , yes these are harmless warnings. It's just skipping regions where there are too many variants called or it looks like a compound set of variants in that location. We have found that it's best not to touch those compound variants. The quality should improve as these are not the most redundant errors.

**Comment by ASLeonard** [comment]
Great, thanks for the clarification.
