### ISSUE TITLE
tmp dir cannot change like deepvariant --intermediate_results_dir

### ISSUE THREAD

**Issue by masen1991** [kishwarshafin/pepper#58]
can u add a optation to make /var/tmp/ is not the dir to wright tmp file ?
when i use Singularity to run (run_pepper_margin_deepvariant call_variant) it may not go well because  /var/tmp/ disk is full.
and i see deepvariant can add  --intermediate_results_dir to change /tmp/ dir.

**Comment by kishwarshafin** [comment]
@masen0407 ,

We explicitly use:
```bash
--intermediate_results_dir= output_dir + "/dv_intermediate_outputs/ "
```
in the docker, so your DeepVariant intermediate outputs should be inside the output directory. Is it not the case in your application? What pipeline are you running?

**Comment by kishwarshafin** [comment]
hi @masen0407 , closing this issue. Please reopen if you don't see the expected behavior in your use case.
