### ISSUE TITLE
nanopore genome calling questions

### ISSUE THREAD

**Issue by RichardCorbett** [kishwarshafin/pepper#59]
Hi there,

I am running using the `pepper-margin-deepvariant-0.4` container in singularity.

My command:
```
   export OMP_NUM_THREADS=1

        /opt/deepvariant/bin/run_deepvariant \
        --model_type=WGS \
        --customized_model=/opt/dv_models/ont_1121_none/model.ckpt-30200 \
        --ref=${reference_fa} \
        --reads=${medaka_bam} \
        --output_vcf=${chromosome_vcf.simpleName}_dv.vcf \
        --num_shards=16 \
        --make_examples_extra_args="alt_aligned_pileup=diff_channels,parse_sam_aux_fields=true,sort_by_haplotypes=true,realign_reads=false,variant_caller=vcf_candidate_importer,proposed_variants=${chromosome_vcf}"
    ```

The extra args came from this nanopore tutorial:
https://nanoporetech.github.io/ont-open-datasets/gm24385_snp/
In the tutorial, the model shown is "/opt/dv_models/ont-3bams-withHP/model.ckpt-33000", but the container I downloaded includes only "/opt/dv_models/ont_1121_none/model.ckpt-30200".   Should I be using "/opt/dv_models/ont_1121_none/model.ckpt-30200"?

The error I am getting with my command is:

> 
> ...
> I0517 12:58:55.025122 140322364766016 make_examples_core.py:163] Task 10/16: Created 5538 examples
> I0517 12:58:57.336977 140560082081600 make_examples_core.py:163] Task 6/16: Found 5063 candidate variants
> I0517 12:58:57.337149 140560082081600 make_examples_core.py:163] Task 6/16: Created 5197 examples
> 
> real    5m40.621s
> user    76m58.857s
> sys     1m7.659s
> 2021-05-17 12:59:05.081558: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
> I0517 12:59:09.058929 140566676567872 call_variants.py:338] Shape of input examples: [100, 221, 8]
> Traceback (most recent call last):
>   File "/projects/rcorbettprj2/2019FFPE/scratch/Bazel.runfiles_z6q5l22t/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 502, in <module>
>     tf.compat.v1.app.run()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/projects/rcorbettprj2/2019FFPE/scratch/Bazel.runfiles_z6q5l22t/runfiles/absl_py/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/projects/rcorbettprj2/2019FFPE/scratch/Bazel.runfiles_z6q5l22t/runfiles/absl_py/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "/projects/rcorbettprj2/2019FFPE/scratch/Bazel.runfiles_z6q5l22t/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 492, in main
>     use_tpu=FLAGS.use_tpu,
>   File "/projects/rcorbettprj2/2019FFPE/scratch/Bazel.runfiles_z6q5l22t/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 351, in call_variants
>     num_channels_in_checkpoint_model, example_shape[2]))
> ValueError: The number of channels in examples and checkpoint should match, but the checkpoint has 6 channels while the examples have 8.
> 
> real    0m11.222s
> user    0m3.072s
> sys     0m0.654s
> I0517 12:59:10.678918 140494828312384 run_deepvariant.py:416] None
> Traceback (most recent call last):
>   File "/opt/deepvariant/bin/run_deepvariant.py", line 421, in <module>
>     app.run(main)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "/opt/deepvariant/bin/run_deepvariant.py", line 414, in main
>     subprocess.check_call(command, shell=True, executable='/bin/bash')
>   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '( time /opt/deepvariant/bin/call_variants --outfile "/projects/rcorbettprj2/2019FFPE/scratch/tmpdpkfwbz6/call_variants_output.tfrecord.gz" --examples "/projects/rcorbettprj2/2019FFPE/scratch/tmpdpkfwbz6/make_examples.tfrecord@16.gz" --checkpoint "/opt/dv_models/ont_1121_none/model.ckpt-30200" )' returned non-zero exit status 1.

Do you have any suggestions to get around the error?

**Comment by kishwarshafin** [comment]
@RichardCorbett ,

We do not support `Medaka-DeepVariant` in this repository. Our models are trained against PEPPER. I'd suggest getting in touch with Medaka developers to see which model they suggest.
