### ISSUE TITLE
Is there a way to force pepper to call all alternative bases ? 

### ISSUE THREAD

**Issue by gchevignon** [kishwarshafin/pepper#60]
Hi Kishwar, 
We are currently testing pepper for variant calling on sample coming from big DNA virus (genome size 200kb) for which we know from Illumina data and from bam observation of ONT reads alignment in tablet that for specific position there is more than one alternative base compared to the reference base (up to 3 different bases compared to the reference). From what I can see in vcf produced by pepper there is only one alternative. Is there a way to force pepper to call all alternative bases ? Thanks a lot !

Obviously I am willing to share with you our bam alignment with the reference fasta.

Best

**Comment by kishwarshafin** [comment]
@gchevignon , sharing the bam and reference will be very helpful and yes, there are parameters you can use to force PEPPER to pick more variants.

**Comment by kishwarshafin** [comment]
@gchevignon ,

I looked at your data last week. Unfortunately, the force calling on your data calls too many spurious variants and finally our model filters out all of them. The method of force calling needs to improve and hopefully, in the next release, we will have something useful. Until then, I am closing this issue. Sorry that it didn't work.
