### ISSUE TITLE
Make examples/images steps occasionally spike on memory usage

### ISSUE THREAD

**Issue by ASLeonard** [kishwarshafin/pepper#61]
Hi Kishwar,
This may just fall under expected variance, but I've noticed on several different sets of data, that both the pepper make_images and deepvariant make_examples steps occasionally spike on memory usage towards the expected end, which generally leads to the job being killed. Is there some modification by pepper at the end of these jobs that might require additional memory? In any case, is the best approach to lower the memory usage controlling the `partition_size`, or do you have any other suggestions?

Thanks,
Alex

**Comment by kishwarshafin** [comment]
@ASLeonard , is this for the polishing pipeline?

**Comment by ASLeonard** [comment]
Yes, for the polishing pipeline.

**Comment by kishwarshafin** [comment]
I re-generated the issue internally. Usually jobs that get stuck on longer reads and a very high coverage face this issue. You can for now use the `partition_size` to reduce memory usage. PEPPER's issue is a bit more intricate, the next release will have PEPPER's memory and run-time issues fixed. But it's a bit far as testing these tools takes a while.

**Comment by ASLeonard** [comment]
Okay great. I'll try some different sizes to see what works.

Thanks for looking into this.
