### ISSUE TITLE
polish bacterial assemblies

### ISSUE THREAD

**Issue by jagos01** [kishwarshafin/pepper#62]
Hello Kishwar,
I enjoyed your talk at LC2021.  I work primarily with bacterial genomes and have used an earlier version of pepper to polish my flye assemblies.  I noticed you now have a method that could be used to polish haploid genomes with pepper r0.4.  Could you please provide the steps required with the current version of pepper to polish flye assembled bacterial genomes.
Thanks,
Scott

**Comment by kishwarshafin** [comment]
@jagos01 ,

Thank you! We are in the process of evaluating the polishing algorithm on smaller genomes. I will hopefully get back to you in two weeks.

**Comment by kishwarshafin** [comment]
hi @jagos01 ,

After testing microbial polishing internally, it looks like we need a newer model for non-human genomes. The current best way to run the pipeline is a bit too elaborate. It's going to take some time to get to that point but I will re-open this issue once we make that available.

**Comment by jagos01** [comment]
Thank you.  I look forward to the new non-human model.
