### ISSUE TITLE
problems about margin phase

### ISSUE THREAD

**Issue by LiShuhang-gif** [kishwarshafin/pepper#63]
Hi，
I've tried to run pepper-Margin-DeepVariant pipeline on Pacbio HiFi data with singularity. However, I've got some problems when doing the optional step —— running margin phase. 
First of all, after this step it looks like I can only generate a VCF file, but in fact I need to generate a GVCF file for Joint Calling. I have seen the process for ONT data and found it is able to set the resulting file to be a GVCF file. So how can I set the final generated file to be a GVCF file when I run the process for PacbioHiFi.

**Comment by LiShuhang-gif** [comment]
In addition, I have another question. 
I expect to use this process to generate a GVCF file for each sample, and then use GLnexus for join-calling to generate a VCF file containing multiple samples. After completing these two steps, is it necessary to use other softwares(eg. WhatsHap) to re-genotyping the VCF files generated through Join-Calling?
Looking forward to your reply. Thanks so much.

**Comment by kishwarshafin** [comment]
@LiShuhang-gif ,

Currently Margin can only phase a VCF file. Producing phased gvcfs with margin is not possible yet. I think the best idea would be to take the gvcf from DeepVariant and phase it with WhatsHap to see if you can get a phased gvcf. Let me know if that worked for you.
