### ISSUE TITLE
Guppy 5 "sup" models for Nanopore variant calling?

### ISSUE THREAD

**Issue by oneillkza** [kishwarshafin/pepper#64]
Hi @kishwarshafin,

Great talk at London Calling! 

I was wondering whether the models you trained on Bonito data are available somewhere for use? We'd really like to test them out on the new guppy 5 "super-accurate" basecalls, which as far as I can tell are effectively Bonito calls.

Thanks!

**Comment by kishwarshafin** [comment]
@oneillkza ,

The models we trained were from Bonito basecaller and without read-qualities. We are in the process of training new models for Guppy 5. It will take a little bit of time as the basecaller change is looking significant.

**Comment by oneillkza** [comment]
Thanks @kishwarshafin -- I've renamed the issue. Looking forward to seeing the new models.

**Comment by kishwarshafin** [comment]
Please see the newest release, took a while, sorry for the delay.
