### ISSUE TITLE
Availability of SV Workflow 

### ISSUE THREAD

**Issue by zhemingfan** [kishwarshafin/pepper#66]
Hi @kishwarshafin , 

I had a chance to look at your presentation in London Calling - I was wondering if the code you've developed integrating `pepper` with `Flye` was publicly available. 

Thanks,
Jeremy

**Comment by kishwarshafin** [comment]
@zhemingfan , not yet sorry. We are still working and testing on it. There are some very subtle things to take care of and we want to make sure the polishing pipeline is not causing harm to the assembly.

**Comment by zhemingfan** [comment]
Okay, thanks @kishwarshafin !
