### ISSUE TITLE
For the phased results in the vcf file

### ISSUE THREAD

**Issue by Yechao94** [kishwarshafin/pepper#73]
Hi @kishwarshafin ,

I am a little bit confused about the results of the GT column in the *phased.vcf.gz file.
The following is one of the results I got
```
3301310 ./.
 378788 0/0
 941751 0|1
 585556 0/1
    700 0|2
  37872 0/2
 947186 1|0
2141002 1/1
    235 1|2
   6636 1/2
    661 2|0
    208 2|1
   9116 2/2
```
What I wonder is why there are still 0/1 (or "/" ) in the results after phased.  Is there any documentation for the explanation of the pepper results?  

Thanks a lot.

**Comment by tpesout** [comment]
Hi @Yechao94 , there are various cases where margin will not phase a heterozygous variant.  I expect that many of these are INDELs or non-PASS variants (we don't attempt to phase either of these), but there are other cases where this happens (a HET SNP without adjacent HETs, a spot where the HMM thinks a DeepVariant-determined HET is actually HOM, or a loci where the model finds an unlikely division of reads and conservatively makes no phasing call).  

If you would like margin to attempt to phase INDELs or non-PASS variants, you can update the margin config settings "phase.onlyUsePassVCFEntries" or "phase.onlyUseSNPVCFEntries" and rerun the final phasing.  However as these are low-confidence variants they may adversely effect the phasing results.  We have not tested these options and do not expect high-quality results.
