### ISSUE TITLE
using ourselves data to train model about pepper-SNP

### ISSUE THREAD

**Issue by willow2333** [kishwarshafin/pepper#75]
hi @kishwarshafin,
I want to train the pepper-snp model on my datas, can I  use the pepper_snp_train.py directly? thank you very much!

**Comment by kishwarshafin** [comment]
hi @willow2333 ,

Yes, you should be able to use the PEPPER SNP train directly.

**Comment by willow2333** [comment]
hi @kishwarshafin 
thank you for your answer,best regards!
