### ISSUE TITLE
PEPPER slow

### ISSUE THREAD

**Issue by Akazhiel** [kishwarshafin/pepper#76]
Hello,

What is the average running time for the whole PEPPER pipeline for variant calling using Nanopore data? I've run it on a 1.6GB BAM file and it's been running for 4 days on a single machine with no GPU and 8 CPUs and it's still not done. Is this a normal behaviour?

Best regards,

Jonatan

**Comment by kishwarshafin** [comment]
@Akazhiel , 

That is not usual. Can you please share the log?

**Comment by Akazhiel** [comment]
Not sure which of the 4 logs is necessary so I'm appending all 4.

[1_pepper_snp.log](https://github.com/kishwarshafin/pepper/files/6746516/1_pepper_snp.log)
[2_margin_haplotag.log](https://github.com/kishwarshafin/pepper/files/6746517/2_margin_haplotag.log)
[3_pepper_hp.log](https://github.com/kishwarshafin/pepper/files/6746518/3_pepper_hp.log)
[4_DeepVariant.log](https://github.com/kishwarshafin/pepper/files/6746519/4_DeepVariant.log)

**Comment by kishwarshafin** [comment]
@Akazhiel ,

What is the coverage of your sample? I'm trying to re-generate this issue internally.

**Comment by Akazhiel** [comment]
@kishwarshafin,

The coverage was around 1-2x since it was a rather small subset. Could this be the reason for the really slow computation time?

**Comment by kishwarshafin** [comment]
yes, we expect around 60x data to run properly, this is picking all the sites. If you want a small subset, I'd recommend align all of the reads and then take one contig to test the program. At 1-2x, everything looks like a variant.

**Comment by kishwarshafin** [comment]
@Akazhiel , please follow this documentation if you are trying to locally evaluate PEPPER.

https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_docker/ONT_variant_calling.md

Closing this issue. Please re-open if this doesn't work for you.
