### ISSUE TITLE
Failed to open file "MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam" : No such file or directory

### ISSUE THREAD

**Issue by LiShuhang-gif** [kishwarshafin/pepper#77]
Hi，
I am using Pepper for SNP Calling based on ONT data. However, The task was interrupted and an error was reported:

```
mv: cannot stat '/public/home/fan_lab/shali/ossutil/PEPPER_call_snp/LCL6/output/*.bam': No such file or directory
[E::hts_open_format] Failed to open file "/public/home/fan_lab/shali/ossutil/PEPPER_call_snp/LCL6/output/MARGIN_PHASED.PEPPER
_SNP_MARGIN.haplotagged.bam" : No such file or directory
samtools index: failed to open "/public/home/fan_lab/shali/ossutil/PEPPER_call_snp/LCL6/output/MARGIN_PHASED.PEPPER_SNP_MARGI
N.haplotagged.bam": No such file or directory
[07-06-2021 22:12:08] ERROR: None]
Traceback (most recent call last):
  File "/usr/local/bin/run_pepper_margin_deepvariant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/run_pepper_margin_deepvariant/run_pepper_margin_deepvariant.py", line 732, in
main
    run_variant_calling(flags)
  File "/usr/local/lib/python3.6/dist-packages/run_pepper_margin_deepvariant/run_pepper_margin_deepvariant.py", line 376, in
run_variant_calling
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time margin phase /public/home/fan_lab/shali/ossutil/PEPPER_call_snp/LCL6/input/data/
LCL6_minimap2_s.bam /public/home/fan_lab/shali/ossutil/PEPPER_call_snp/LCL6/input/data/hg38_22_XYM.fa /public/home/fan_lab/sh
ali/ossutil/PEPPER_call_snp/LCL6/output/PEPPER_SNP_OUPUT.vcf.gz /opt/margin_dir/params/misc/allParams.ont_haplotag.json -t 22
 -V -o /public/home/fan_lab/shali/ossutil/PEPPER_call_snp/LCL6/output/MARGIN_PHASED.PEPPER_SNP_MARGIN 2>&1 | tee /public/home
/fan_lab/shali/ossutil/PEPPER_call_snp/LCL6/output/logs/2_margin_haplotag.log;
mv /public/home/fan_lab/shali/ossutil/PEPPER_call_snp/LCL6/output/*.bam /public/home/fan_lab/shali/ossutil/PEPPER_call_snp/LC
L6/output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam;
samtools index -@22 /public/home/fan_lab/shali/ossutil/PEPPER_call_snp/LCL6/output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagge
d.bam' returned non-zero exit status 1.
```
By the way, I don't have this input file, I think it's an intermediate file generated by Pepper-Margin-Deepvariant pipeline.
Any suggestions? Thanks ever so much.

**Comment by kishwarshafin** [comment]
@LiShuhang-gif , 

Can you please see if PEPPER_SNP finished successfully? There should be a log there.

**Comment by LiShuhang-gif** [comment]
> @LiShuhang-gif ,
> 
> Can you please see if PEPPER_SNP finished successfully? There should be a log there.

Yes, there is a log file 1_pepper_snp.log. So I think this step finished successfully.
And I upload the complete log file which contains the error messages: [PEPPER_LCL6.log](https://github.com/kishwarshafin/pepper/files/6774077/PEPPER_LCL6.log)

**Comment by kishwarshafin** [comment]
```bash
Expected three tokens in header line, got 2


real	113m25.641s
user	1881m15.316s
sys	77m53.155s
```

This is an error that we have seen previously. Please see this [issue](https://github.com/kishwarshafin/pepper/issues/67). Similar to this issue can you see if your bam is corrupted or have duplicate reads?
```bash
samtools view -F 0x900 -q 10 INPUT.bam | cut -f1 | uniq -c | awk '$1 > 1' | head
```

**Comment by LiShuhang-gif** [comment]
> ```shell
> Expected three tokens in header line, got 2
> 
> 
> real	113m25.641s
> user	1881m15.316s
> sys	77m53.155s
> ```
> 
> This is an error that we have seen previously. Please see this [issue](https://github.com/kishwarshafin/pepper/issues/67). Similar to this issue can you see if your bam is corrupted or have duplicate reads?
> 
> ```shell
> samtools view -F 0x900 -q 10 INPUT.bam | cut -f1 | uniq -c | awk '$1 > 1' | head
> ```

Thank you for your suggestion. I am trying to use Picard to remove the duplicated reads in my bam file and then run PEPPER-Margin-DeepVariant pipeline again. I'll let you know if it works well.

**Comment by kishwarshafin** [comment]
thank you @LiShuhang-gif , please re-open this issue if you have any trouble after removing duplicates.
