### ISSUE TITLE
How to generate aligned haplotype BAMs for training PEPPER-HP?

### ISSUE THREAD

**Issue by TimD1** [kishwarshafin/pepper#78]
Hi @kishwarshafin,

I'm trying to re-train PEPPER-HP, but the input required by `pepper_hp_train` is a little weird.

If my files are:
```
$ref="GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta"
$vcf="HG002_GRCh38_1_22_v4.1_draft_benchmark.vcf.gz"
$bam="margin-output.haplotagged.bam"
```
I need to apply the SNPs in `$vcf` to `$ref`, while using the phasings from `$bam`. I cannot directly apply the SNPs in `$vcf` to `$ref` like this:
```
samtools faidx \
    $ref \
    $chr:$start-$stop | \
bcftools consensus \
    $vcf \
    -H 1pIu \
    -o hap1.fasta
./align \
    hap1.fasta \
    $ref \
    -o hap1.bam
...
pepper_hp_train make_train_images \
    -b $bam \
    -f $ref \
    -tb1 hap1.bam \
    -tb2 hap2.bam \
    -rb train.bed \
    -o ./train_img/
```
since `$vcf` likely contains different phasings than `$bam`. I need to first phase `$vcf` so that phasings are consistent with `$bam`, and the ground-truths for hap1 and hap2 are correctly phased while training PEPPER-HP. Is there a way to do this, provided by either Margin or PEPPER? `margin polish` has some promising flags like `--vcf`, `--diploid`, `--tempFilesToDisk`, and `--onlyVcfAlleles`, but I haven't yet figured out how to get it to do what I want. I could always write my own script to do this, but I'd prefer not to, and suspect there's already a solution. 

Thanks in advance!
-Tim

**Comment by TimD1** [comment]
Never mind, it looks like `whatshap` has the functionality I'm looking for. I'll just use that instead!

**Comment by TimD1** [comment]
Reopening. For some reason `whatshap` and `bcftools` have been causing a headache with invalid formatting of VCF files. Is there a recommended workflow for generating the aligned haplotypes?

**Comment by kishwarshafin** [comment]
hi @TimD1,

We obtained a phased VCF from GIAB that you can find here:
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/SupplementaryFiles/

You may have to fix a few things in the VCF if you encounter errors with whatshap.

**Comment by TimD1** [comment]
Thanks for explaining where you obtained your phased VCF. 

However, that doesn't really answer my main question: once you have a phased VCF, how did you convert it to a BAM of aligned haplotypes, phased with respect to the reads?

**Comment by kishwarshafin** [comment]
You can use `whatshap` to get the phased bam.

**Comment by kishwarshafin** [comment]
I think I see what you mean, you want the aligned haplotypes, so we take the VCF, convert it to two fasta files and align the sequences back to GRCh38 using minimap2/dipcall, giving us two haplotype alignment of the truth.
