### ISSUE TITLE
Question on downsampling fractions used in the article

### ISSUE THREAD

**Issue by lbal-biomat** [kishwarshafin/pepper#79]
Hi, this is not really an issue but a question.
I'm re-running some of the runs of the article to make sure I can reproduce it nicely before doing my own analysis.
I'm unsure what fractions you have used to downsample the bam file. I was thinking it was something like `samtools view -s 0.3` for 30X and so on, but then realize that it wouldn't give me exactly 30X, I would need a 1/3, problem being that it's not possible to represent it precisely with decimals. Can you hive me a hint on what you used for the different downsamples?
Thanks in advance!

**Comment by kishwarshafin** [comment]
Hi @lbal-biomat ,

`0.3` of 30x coverage would give you 10x coverage in general. We used up to 2 decimal points if that's what you are asking.

**Comment by lbal-biomat** [comment]
HI @kishwarshafin ,
Thanks for your answer, yes the question was about decimal points indeed.
I'm closing the issue. Thanks again.
