### ISSUE TITLE
Run only candidate finding algorithm

### ISSUE THREAD

**Issue by marcus1487** [kishwarshafin/pepper#8]
As per our discussion on Twitter, I am interested in running just the candidate finding portion of the algorithm.

For more background, I’m interested a data driven algorithm to feed variants into Megalodon (which does not discover variants, but just scores them). This sounds like the perfect solution. I look forward to testing out pepper!

**Comment by kishwarshafin** [comment]
Hi Marcus, 

Sounds like PEPPER can give you a pretty good solution for this. The quickest and best way to run `PEPPER_SNP` would be to run these commands:
```bash
git clone https://github.com/kishwarshafin/pepper.git
cd pepper
make install
source ./venv/bin/activate
```
Once you have successfully installed PEPPER, you can simply run:
```bash
pepper_snp call_variant \
-b <bam_file> \
-f <reference_file> \
-m <PEPPER_SNP_model> \
-o <output_dir> \
-s <sample_name> \
-t <number_of_threads> \
-r chr1-22,chrX,chrY \ # set regions, if not set, all regions will be processed
-p 0.1 \ # you can change this value to your setting, higher will trade recall for precision.
-g # remove this if you are not using GPU
```

Please download the SNP model from here:
```bash
wget https://storage.googleapis.com/kishwar-helen/variant_calling_data/pFDA_v2/Nanopore/PEPPER_trained_models/PEPPER_SNP_R941_guppy360_model.pkl
```

Please let me know if you need a docker, that's also fairly easy to make.

**Comment by marcus1487** [comment]
This looks perfect! I will give this a go and report back. Thanks so much for the quick reply and amazing work.

**Comment by kishwarshafin** [comment]
Hi @marcus1487 ,

I'm going to close this issue for now. Please re-open if you need further assistance.
