### ISSUE TITLE
difference of model structure  between pepper and helen

### ISSUE THREAD

**Issue by willow2333** [kishwarshafin/pepper#80]
@kishwarshafin hi，
could you please help me understand the difference of model structure  between pepper and helen, i have seen the raw code of the two models,   thery are very similar about RNN. Also i found 'get_new_model' function  in pepper codes,the function contain 'EncoderCRNN' and 'AttnDecoderRNN', but i cannot find where they are bused. thanks a lot !

**Comment by kishwarshafin** [comment]
@willow2333 ,

`HELEN` uses run-length encoding and `PEPPER` does not, that's a broader scale difference. Another difference is that we designed PEPPER to be a variant caller rather than a polisher and will continue to move in that direction.

**Comment by willow2333** [comment]
@kishwarshafin ，
thanks for your answer,can i  think that it  same about polisher RNN model between PEPPER and HELEN, only consider network structure. thanks a lot !
