### ISSUE TITLE
Make example step in nanopore polishing slows drastically at the end

### ISSUE THREAD

**Issue by ASLeonard** [kishwarshafin/pepper#82]
Hi Kishwar,
I noticed another strange change in behaviour for the deepvariant make_example step in the nanopore polishing pipeline. It seems like you found the problem in #61 with regards to memory, but I've noticed in a different dataset that memory seems to be fine, but now it is the time that spikes.

![image](https://user-images.githubusercontent.com/29678761/127040568-82bea346-ec8a-49b2-9329-bf7eb29defcb.png)

Most 100 examples take only a few seconds, but towards the end, start taking up to 2000 seconds per 100, which is a huge spike.

It may be related to whatever caused the memory issue, so potentially already fixed, but v0.4.1 appears to still be the latest non-test release available. 

Thanks,
Alex

**Comment by kishwarshafin** [comment]
@ASLeonard , these are possibly contigs that attract a lot of reads because of missing contiguity. I think I have been able to replicate this locally. The solution doesn't seem very easy, I will keep you updated, but, unlikely it'll be solved in the next release.

**Comment by ASLeonard** [comment]
Great, thanks for taking a look at it.
