### ISSUE TITLE
Polishing with short reads

### ISSUE THREAD

**Issue by wchow** [kishwarshafin/pepper#83]
Hi, great tool. Just a general question:

I am interested in the polishing of nanopore assemblies and remember one of the speakers during London Calling mentioning potentially using pepper to polish with short reads/long reads.  My general question is, has this been tried with pepper using illumina short reads and if so, do you think it can be applied to metagenomic datasets.

thanks

Will

**Comment by kishwarshafin** [comment]
Hi @wchow ,

PEPPER is designed for long reads. The best way to use PEPPER-DeepVariant is described here:
https://www.biorxiv.org/content/10.1101/2021.07.02.450803v1
which is primarily used to polish this assembly:
https://www.biorxiv.org/content/10.1101/2021.05.26.445798v1
