### ISSUE TITLE
present of overlay in my filesystem

### ISSUE THREAD

**Issue by zhoudreames** [kishwarshafin/pepper#85]
when i fail to run the pepper，there is overlay present in my filesystem by using “df -h ”，how to delete it ？
![image](https://user-images.githubusercontent.com/54714639/128832088-9b59ceab-8299-41cd-96cf-f3fab93fcb83.png)

**Comment by kishwarshafin** [comment]
@zhoudreames , this seems most relevant for you: https://stackoverflow.com/questions/31712266/how-to-clean-up-docker-overlay-directory
