### ISSUE TITLE
precisionFDA Truth Challenge V2 - link broken

### ISSUE THREAD

**Issue by tararickman** [kishwarshafin/pepper#87]
Hi @kishwarshafin , 

I came across your pipeline in the [precisoinFDA Truth Challenge V2 paper](https://www.biorxiv.org/content/10.1101/2020.11.13.380741v4.supplementary-material) and am excited to use your approach for variant calling! Within the supplemental material, on page 5, there is a section named "Variant caller" and within here is the following "Parameters and details posted here: https://github.com/kishwarshafin/pepper/blob/master/docs/PEPPER_variant_calling.md" ; however, this takes me to 404 page not found. Has this file been moved elsewhere within the repository and if so would you be able to direct me where I can find it?

Thank you!

**Comment by kishwarshafin** [comment]
@tararickman ,

An updated manuscript is here: https://www.biorxiv.org/content/10.1101/2021.03.04.433952v1.

You can follow the tutorial from here: https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_docker/ONT_variant_calling.md
