### ISSUE TITLE
Problem with ambiguity characters in v0.5

### ISSUE THREAD

**Issue by GuillaumeHolley** [kishwarshafin/pepper#90]
Hi,

I am currently running PEPPER v0.4 for some Illumina-corrected ONT reads (Guppy 3.6) of HG002 and the results are very good. On chr1:0-5,000,000, F-measure is 98.78% with the CCS mode and 98.18% with the ONT mode.

I tried PEPPER v0.5 this morning on the same raw and corrected data, no change in parameters:

1. PEPPER v0.5 does not output any variants for the corrected data in ONT mode (while v0.4 did). It seems `pepper_variant` has some errors of the type `ERROR IN THREAD: 'M'`. My corrected ONT reads do indeed contain ambiguity characters in some reads as SNP candidates that couldn't be corrected with enough accuracy. Is it a problem in this new version?
2. I ran PEPPER v0.4 and v0.5 on the raw ONT reads for the same region. v0.4 gives me 97.57% F1 while v0.5 gives me 96.63% F1, so a non-negligible decrease of performance with this new version.

Thank you for the help!

Guillaume

**Comment by kishwarshafin** [comment]
@GuillaumeHolley , Thank you for opening the issue.

1) Will it be possible to provide a small test case that I can incorporate internally? I can't say where it breaks without either looking at the log or having an internal test. We did change the pileup creation scheme significantly which may have caused these issues. Instead of generating summaries of the entire chromosome, we now go to specific locations and generate summaries of the nearby reads.

2) Are you using Guppy 3.6.0 reads? Those reads are fairly old and have a very high error rate. This version is trained on Guppy 5.0.7 "sup" with the only pass reads. I think the delta is coming from the difference in the basecaller version. Here's the difference between previous versions of the basecaller against guppy 5.0.7 on the same reads:
![Read_identity_guppy422_vs_guppy507_2](https://user-images.githubusercontent.com/10559039/131137722-d08680a3-bdb1-4bdd-bf85-9a4ac76a7009.png)

**Comment by GuillaumeHolley** [comment]
1. Good to know. I just uploaded a small region of the HG002's corrected ONT data matching chr1:2,500,000-3,000,000 -> [hg002.corrected.subsample.zip](https://github.com/kishwarshafin/pepper/files/7068109/hg002.corrected.subsample.zip). PEPPER v0.5 does output variants for this region up to chr1:2,759,595 and then nothing afterwards. Even the variants it outputs are suspicious.
2. For now I am indeed using Guppy 3.6.0 reads for HG002 because it is an older dataset I had downloaded a while ago. Hopefully, I'll be able to test Guppy 5.0.x soon. But this older dataset is convenient for me at the moment because a very large number of our samples in-house are basecalled with Guppy 3.x.x / 4.x.x. Re-basecalling all of it with Guppy 5.x.x, especially with the SUP model which takes a while, will take some time. And in the meantime, I am working with these. I understand that the new PEPPER is trained for the latest Guppy with the SUP model, maybe it would good to provide multiple models within PEPPER and let the user choose the one it wants as an option?

Thanks for having a look into this!

**Comment by kishwarshafin** [comment]
@GuillaumeHolley ,

Thanks for the data I will take a look very soon.

Supporting multiple basecallers is a bit difficult, we will need a little bit of time to go through all of the testing for an older basecaller and it severely hampers the speed we want to have to explore algorithmically. But, I understand your frustration. If your application is time-sensitive then please use `r0.4` for now, I'll take a note internally to see if we can at least incorporate guppy v4.2.2 with the newest features.

**Comment by GuillaumeHolley** [comment]
I can only imagine how complicated it is to support multiple (older) basecallers while trying to push forward with algorithmic advances. We will definitely follow your advice and stick with r0.4 for the time being. I would still suggest a small note in the README about this: Guppy 5.0.x -> r0.5, otherwise r0.4?

**Comment by kishwarshafin** [comment]
@GuillaumeHolley , just to keep you updated, I've fixed this issue internally, thank you for sharing the input. I will push a new docker hopefully today after I look at another bug. Will also update the readme. Thanks for your patience.

**Comment by GuillaumeHolley** [comment]
@kishwarshafin I do appreciate you took the time to work on this, I can't wait to try it. I have downloaded a Guppy 5.0.x HG002 dataset and the results post-correction for a subsample are very promising compared to Guppy 3.6. I should have the full corrected data set next week.

Thank you!

**Comment by kishwarshafin** [comment]
@GuillaumeHolley , I have pushed the new docker.

Please run:
```
docker pull kishwars/pepper_deepvariant:r0.5
```
And then run:
```
time docker run -it -v /data:/data \
kishwars/pepper_deepvariant:r0.5 \
pepper_variant --version
```
This should give you `PEPPER VERSION:  0.5.2` which should have your issue fixed. Please feel free to reopen if you face any other issues.

**Comment by GuillaumeHolley** [comment]
I can confirm here the new version works fine with ambiguity characters.
