### ISSUE TITLE
Feature request: reopen #56

### ISSUE THREAD

**Issue by SHuang-Broad** [kishwarshafin/pepper#92]
Multiple regions i.e. a list of regions after `-r`.

**Comment by SHuang-Broad** [comment]
My splitting scheme will be based on large reference gaps (so will not work for T2T but I'm willing to sacrifice).
This means long range information for phasing won't be available as that will be interrupted by large gaps, if I understand correctly.

Thanks!

**Comment by kishwarshafin** [comment]
@SHuang-Broad this can be achieved upstream of PEPPER-DeepVariant. Is there any specific benefit of doing it internally? You will not get the parallelization benefit by simply having the flag take multiple regions?

**Comment by SHuang-Broad** [comment]
You are correct, and that is indeed what I ended up doing this afternoon.
Thanks!
