### ISSUE TITLE
how to use guppy 5 model

### ISSUE THREAD

**Issue by RichardCorbett** [kishwarshafin/pepper#93]
Good morning!

I am trying out your new release and hoping to use the guppy 5 model.  Do I need to specify the model to use?  I don't see the parameter to pass in.

My command
```
singularity exec -B /projects/   pepper_deepvariant_r0.5.sif run_pepper_margin_deepvariant call_variant -b F16406.sorted.guppy5.bam -f hg19a.fa -t 96 -o guppy_5 --ont --phased_output​ --gvcf -p F16406.sorted.guppy5 
```

**Comment by RichardCorbett** [comment]
Noting that after I fired up the command above it appears that pepper is using a guppy5 model.   I see this process running now...
"/usr/local/bin/pepper_variant call_variant -b ../clair_v3/F16406.sorted.guppy5.bam -f ../clair_v3/hg19a.fa -t 96 -m /opt/pepper_models/PEPPER_VARIANT_R941_ONT_V5.pkl -o ..."

**Comment by kishwarshafin** [comment]
@RichardCorbett guppy 5 is default with the newest release. r0.5=guppy5, r0.4=guppy4
