### ISSUE TITLE
Feature request: decreasing the size of the image

### ISSUE THREAD

**Issue by SHuang-Broad** [kishwarshafin/pepper#94]
The size of the image (tag `r0.4.1`) is 12.8GB.

For deployment on the cloud, particularly when the genome is sharded into many intervals, pulling such a large docker takes time.

So I am willing to help with shrinking the size of the image.

Thanks,
Steve

**Comment by kishwarshafin** [comment]
@SHuang-Broad , I want to understand your use-case better. What exactly are you trying to achieve? r0.4.1 is big because we released CUDA and CPU within the same docker, `v0.5-cpu` is much smaller in that regard.

**Comment by SHuang-Broad** [comment]
This is related to the way we shard genomes: approximately 20 shards for the human genome.

We develop pipelines using WDL and Cromwell, which does parallelization differently from HPC clusters.
Basically, for one sample, the system commissions one VM&mdash;from a cloud service provider (AWS, Azure, GCP...)&mdash;for each shard, this means each VM will be pulling the Pepper docker for itself.
So when the number of samples increase, the number of pulls multiply: e.g. for 10 samples, there will be approximately 200 pulls.

And for a typical sample, this means the size of the docker image pulled is roughly equal to, if not bigger than, the BAM itself.

**Comment by kishwarshafin** [comment]
Ok, if you are doing everything on VMs, would it not be simpler to create a base image for the instance that has everything you need installing internally instead of pulling the docker every time? If you have an image ready and start from there then the pull can be completely avoided.

**Comment by SHuang-Broad** [comment]
I agree that "mounting" the data disk on to the "computation" disk is the preferred solution, but currently the cloud computing service we rely on doesn't offer that ideal solution. Every computation is done on-demand, which means the image is pulled every time at the beginning of a task. The VM is turned off every time the task is finished, and gone with it is the disk performing the computation (results are saved to cloud storage before that). So the API we are currently using doesn't offer the option of "keeping the docker" (keeping the docker means keep the disk, which incurs cost in cloud computing). 

So the option we have—at when we have control—is to minimize the docker image itself.

**Comment by SHuang-Broad** [comment]
Anyway, I did some investigation into which directory seem to use the most space, and below are my findings.

## General suggestion:

* remove `pip` cache in `/root/.cache/pip`; this can be done via `pip cache purge`; maybe the Dockerfile can also make use of `--no-cache-dir` when installing pip packages


## Sequencing-technology-specific suggestion:

Apparently, this is a trade-off and cannot be generalized to every user

* pick the needed model in `/opt/dv_models` and/or `/opt/models`

---------------------

Disk space usage

## `/`

```bash
0	dev
0	proc
0	sys
4.0K	boot
4.0K	home
4.0K	lib64
4.0K	media
4.0K	mnt
4.0K	srv
4.0K	tmp
20K	run
2.2M	etc
3.8M	sbin
5.0M	bin
14M	lib
15M	var
1.2G	root
3.0G	opt
6.5G	usr
```

### `/usr`

```
4.0K	games
428K	src
2.2M	sbin
59M	share
66M	bin
165M	include
1.6G	lib
4.7G	local
```

#### `/usr/local`

```
0	cuda
0	man
4.0K	etc
4.0K	games
4.0K	include
4.0K	src
8.0K	sbin
1.2M	share
3.0M	libexec
15M	bin
2.0G	cuda-10.1
2.6G	lib
```

#### `/usr/local/lib/python3.6/dist-packages`

```
...
811M	tensorflow
1.3G	torch
```

### `/opt`

```
20K	licenses.zip
3.7M	bcftools-1.11.tar.bz2
4.6M	samtools-1.11.tar.bz2
19M	pepper_models
49M	deepvariant
58M	bcftools-1.11
75M	samtools-1.11
106M	cmake
128M	margin_dir
1.1G	dv_models
1.5G	models
```

#### `/opt/dv_models`

```
366M	202012_polish_ccs_hp_rows
366M	202012_polish_nohp_rows
366M	ont_1121_none
```

#### `/opt/models`

```
366M	hybrid_pacbio_illumina
366M	pacbio
366M	wes
366M	wgs
```

**Comment by kishwarshafin** [comment]
@SHuang-Broad , I'll look into this, at least for release 5 I can work on reducing the size, I think I understand the use-case better.

**Comment by kishwarshafin** [comment]
@SHuang-Broad ,

I tried some of the suggestions, it didn't help much, I'll debug a little bit more but need to push this back for now.
