### ISSUE TITLE
PEPPER_VARIANT_OUTPUT_PHASING.vcf missing 

### ISSUE THREAD

**Issue by masen1991** [kishwarshafin/pepper#96]
As i try use PEPPER VERSION: 0.5.2 , at end of  pepper_variant step , error like Could not read from vcf file:PEPPER_OUTPUT_SNP.vcf.gz
following case-study and i can generate the final table.
i use 16 cpus and mem like this :
              total        used        free      shared  buff/cache   available
Mem:          125Gi       8.3Gi        11Gi       0.0Ki       106Gi       116Gi
Swap:         8.0Gi       135Mi       7.9Gi
Will this happen with  mem insufficient ?
the bam is 151G large. 
[1_pepper.log](https://github.com/kishwarshafin/pepper/files/7109167/1_pepper.log)
[2_margin_haplotag.log](https://github.com/kishwarshafin/pepper/files/7109168/2_margin_haplotag.log)
[4_DeepVariant.log](https://github.com/kishwarshafin/pepper/files/7109169/4_DeepVariant.log)

**Comment by kishwarshafin** [comment]
@masen0407 , I am a bit confused by this. So you are saying:

1) You are able to run our pipeline on the test HG002 chr20 data we provided?

2) It does not work on the data you have internally, and it fails after image generation step of PEPPER?

I have a few questions for you in that case:
1) What basecaller you used for your internal data? The current version of PEPPER is trained on guppy 5.0.7 "sup", if you are using older basecallers then the error-rate would be high and it would pick up more candidates than it should.

2) What is the sample? Is it a diploid human genome sample?

3) What was the command you used to align the reads to the reference? Please provide the minimap2 command.

4) What reference are you using? From your previous logs, it seems you are using GRCh38 with alts, current variant callers can't take advantage of alt sequences, you should use GRCh38 with no_alts. They are available here:
https://storage.googleapis.com/kishwar-helen/variant_calling_data/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
https://storage.googleapis.com/kishwar-helen/variant_calling_data/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fai

**Comment by masen1991** [comment]
@kishwarshafin 
Sorry i did not describe very well.
i meet some error just as u say:
You are able to run our pipeline on the test HG002 chr20 data we provided?
It does not work on the data you have internally, and it fails after image generation step of PEPPER?

and
1.sorry i don't know the basecaller of my ONT samples,i may need some time to confirm this one. i just get the mapped bam file.
2.It is diploid human genome sample.And i try more than one sample,it all get this error.
3.the command like this :minimap2 -ax map-ont --MD hg38_ref.fasta *fastq.gz 
4.the  reference i use GRCh38_no_alt_plus_hs38d1_analysis_set.fa is a kind of no alts reference.
https://googlegenomics.readthedocs.io/en/latest/use_cases/discover_public_data/reference_genomes.html#verily-s-grch38
Verily’s GRCh38:
excludes all patch sequences
omits alternate haplotype chromosomes
includes decoy sequences
masks out duplicate copies of centromeric regions
in this ftp: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/
 u may see both your recommend GCA_000001405.15_GRCh38_no_alt_analysis_set.fna and GRCh38_no_alt_plus_hs38d1_analysis_set.fna which i use,it both have no alts.

BTW i can use kishwars/pepper_deepvariant:r0.4 cpu version to get a results on this samples.
i already have the reaults,then i use the same bam file to try kishwars/pepper_deepvariant:r0.5-gpu and i get error like i said before .

Sorry again for i did not  make it clear.

**Comment by kishwarshafin** [comment]
@masen0407 , 
That is inconsistent behavior, can you share one bam file with me with the associated reference? I can look at the log in debug mode to see what's going on. I will be out for a bit, I can look at it in two weeks.

**Comment by masen1991** [comment]
@kishwarshafin  
 i notice this 
NOTE: The models of v0.5PEPPER v0.4 are trained with Guppy v5.0.7 "sup" mode. If you use have Guppy v4.X data, please use PEPPER v0.4

So maybe it happen because Guppy version and my samples can only work on PEPPERv0.4 .
i cannot share my bam file because some other reason(i have limits of authority to do this),i have downloads giab 
 HG002_NA24385_son Ultralong_OxfordNanopore:
https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/guppy-V3.2.4_2020-01-22/
i will try v0.5 work on guppy-V3.2.4 bam file .

Will you update PEPPER v0.4 GPU version to have sm_70, sm_80 support for the 30XX RTX cards?
So i can use PEPPER v0.4 GPU version  on Pacbio HIFI reads and ONT reads?

**Comment by kishwarshafin** [comment]
@masen0407 v0.4 can't support `sm_80` because the internal libraries we used were from before CUDA 11.2 was released. I tried to update the base image, but, was not able to install it properly. I ran v0.5 on all seven GIAB samples and I didn't see any issues. As you can't share the data, and, I can't replicate the error locally, I will close this issue as unresolvable.

**Comment by masen1991** [comment]
@kishwarshafin 
i try  HG002 Ultralong_OxfordNanopore_guppy-V3.2.4 sample and meet the same error , so the reason may as u said:
The current version of PEPPER is trained on guppy 5.0.7 "sup", if you are using older basecallers then the error-rate would be high and it would pick up more candidates than it should.
Because i can also use r0.4 on this HG002 Ultralong_OxfordNanopore_guppy-V3.2.4 sample.
It may can not work well on other guppy version data.

**Comment by kishwarshafin** [comment]
@masen0407 guppy 3.2.4 is too old for this pipeline. The first release of PEPPER used guppy 4.2.2 so we expect users to use the latest basecaller while using our pipeline. Guppy 3.2.4 has a 5% error rate compared to 1.5% guppy 5.0.7 "sup". It is not possible to support a version so old. I would strongly suggest re-basecalling you data and use the lastest version, that will give you the best results for any downstream study you want to do with your sample.

**Comment by masen1991** [comment]
> . I would strongly suggest re-basecalling you data and use the lastest version, that will give you the best results for any downstream study you want to do with your sample.

Thank for your replay.I use Guppy 3.2.4 data because GIAB only share guppy (version 3.X ) public data.
i will check agagin for my data and pay more attention on different  basecaller methods.

**Comment by kishwarshafin** [comment]
@masen0407 , please see the supplementary pdf of this paper: https://www.biorxiv.org/content/10.1101/2021.03.04.433952v1.abstract

You can follow more data here: https://github.com/human-pangenomics/HG002_Data_Freeze_v1.0

**Comment by masen1991** [comment]
> @masen0407 , please see the supplementary pdf of this paper: https://www.biorxiv.org/content/10.1101/2021.03.04.433952v1.abstract
> 
> You can follow more data here: https://github.com/human-pangenomics/HG002_Data_Freeze_v1.0

Great!Thanks a lot for share these informations.
BTW, if i use PEPPER v0.4 on guppy version 3.X data and i can get a results,do this way recommanded?
Or may as u said PEPPER should work on guppy 4.X and guppy 5.X?
because some of our data can not easily do re-basecalling.
And thank again for your patiently replay. It is really a good tools work on TGS reads as i try use clair and longshot at the same time.

**Comment by kishwarshafin** [comment]
@masen0407 PEPPER v0.4 is the best bet you have. I remind you that precisionFDA v2 happened on guppy 4.2.2 so that's the first model we released. So re-basecalling is preferred. You are welcome to re-open the issue if you face trouble on newer data.
